import { defineTool, type ToolManifest } from "@/tools/registry";

export * from "@/tools/registry";
export * from "@/tools/categories";

/**
 * سجلُّ أدوات Do Kits.
 * إضافةُ أداةٍ = عنصرٌ واحدٌ هنا + مجلّدُ `tools/<slug>/`. لا شيءَ آخر.
 */
export const TOOLS: ToolManifest[] = [
  /* ————— نصوص ومستندات ————— */
  defineTool({
    slug: "word-counter",
    title: "عدّاد الكلمات العربيّ",
    titleEn: "Arabic Word Counter",
    description: "كلماتٌ وحروفٌ وجملٌ وزمنُ قراءة — يفهم العربيّةَ وتشكيلَها، ولا يغادر النصُّ متصفّحَك.",
    category: "docs", subcategory: "analysis", icon: "counter", version: "1.0.0",
    keywords: ["عدد الكلمات", "عدد الحروف", "زمن القراءة", "إحصاء", "فقرات", "جمل"],
    keywordsEn: ["word count", "character count", "reading time"],
    instructions: "ألصق نصّك ليُحسَب فوراً — لا يُرسَل شيءٌ إلى الخادم.",
    howItWorks: [
      "الكلمةُ كلُّ تتابعٍ من حروفٍ أو أرقام، فلا تُعدّ علاماتُ الترقيم كلمات.",
      "«بلا تشكيل» يحذف الحركاتِ والتطويلَ قبل العدّ — وهو ما يهمّ عند حساب طول النصّ الفعليّ.",
      "زمنُ القراءة على أساس ١٨٠ كلمةً في الدقيقة، وهو متوسّطُ القراءة العربيّة.",
    ],
    load: () => import("@/tools/word-counter/tool"),
  }),
  defineTool({
    slug: "strip-diacritics",
    title: "إزالة التشكيل",
    titleEn: "Remove Diacritics",
    description: "تجريدُ النصّ من التشكيل والتطويل، وتوحيدُ الألف والتاء للبحث والمطابقة.",
    category: "docs", subcategory: "cleanup", icon: "eraser", version: "1.0.0",
    keywords: ["تشكيل", "حركات", "تطويل", "همزة", "توحيد", "بحث", "مطابقة"],
    keywordsEn: ["diacritics", "tashkeel", "normalize arabic"],
    instructions: "اختر ما تريد إزالتَه، وسيُطبَّق على النصّ فوراً.",
    howItWorks: [
      "إزالةُ التشكيل والتطويل لا تمسّ الإملاء — النصُّ يبقى صحيحاً للنشر.",
      "توحيدُ الألف (أ إ آ ← ا) والتاء (ة ← ه) يغيّر الإملاء، فهو للبحث والمطابقة لا للنشر.",
      "المحارفُ الخفيّة تُحذف أيضاً، وهي أشهرُ سببٍ لبحثٍ لا يجد ما تراه العين.",
    ],
    load: () => import("@/tools/strip-diacritics/tool"),
  }),
  defineTool({
    slug: "arabic-numerals",
    title: "تحويل الأرقام",
    titleEn: "Arabic ↔ Latin Numerals",
    description: "بين العربيّة-الهنديّة (٠١٢) واللاتينيّة (012) داخل نصٍّ كامل.",
    category: "docs", subcategory: "format", icon: "digits", version: "1.0.0",
    keywords: ["أرقام عربية", "أرقام هندية", "٠١٢", "تحويل أرقام", "فارسية"],
    keywordsEn: ["arabic numerals", "eastern arabic digits"],
    instructions: "ألصق نصّاً فيه أرقام واختر الاتّجاه.",
    howItWorks: [
      "يبدّل الأرقامَ داخل النصّ ويترك الحروفَ والرموزَ كما هي.",
      "الأرقامُ الفارسيّة (۰۱۲) تُقبل أيضاً وتُحوَّل إلى اللاتينيّة.",
    ],
    load: () => import("@/tools/arabic-numerals/tool"),
  }),
  defineTool({
    slug: "keyboard-fix",
    title: "تصحيح لوحة المفاتيح",
    titleEn: "Keyboard Layout Fixer",
    description: "نصٌّ كُتب والتخطيطُ خاطئ يعود إلى لغته الصحيحة.",
    category: "docs", subcategory: "cleanup", icon: "keyboard", version: "1.0.0",
    keywords: ["لغة خاطئة", "تخطيط", "طلاسم", "معرّب", "كتابة خاطئة", "qwerty"],
    keywordsEn: ["keyboard layout", "wrong language", "transliterate keys"],
    instructions: "ألصق النصّ المبهم — يُخمَّن الاتّجاه تلقائيّاً.",
    howItWorks: [
      "يعتمد تخطيطَ لوحة المفاتيح العربيّة القياسيّة (١٠١) مقابل QWERTY.",
      "الحروفُ المركّبة مثل «لا» و«لأ» تُعامَل مفتاحاً واحداً كما هي في اللوحة.",
      "التخمينُ يقارن عددَ الحروف العربيّة باللاتينيّة، ويمكنك تجاوزُه يدويّاً.",
    ],
    load: () => import("@/tools/keyboard-fix/tool"),
  }),
  defineTool({
    slug: "clean-text",
    title: "تنظيف النصّ",
    titleEn: "Text Cleaner",
    description: "مسافاتٌ زائدةٌ وأسطرٌ فارغةٌ ومحارفُ خفيّةٌ تفسد البحث.",
    category: "docs", subcategory: "cleanup", icon: "broom", version: "1.0.0",
    keywords: ["مسافات", "أسطر فارغة", "محارف خفية", "ترقيم", "تنسيق"],
    keywordsEn: ["clean text", "whitespace", "invisible characters"],
    instructions: "فعّل ما يلزمك من خيارات التنظيف.",
    howItWorks: [
      "«المحارفُ الخفيّة» تشمل الوصلاتِ والعلاماتِ الاتّجاهيّةَ التي لا تُرى وتفسد المطابقة.",
      "«ضبطُ الترقيم» يحذف المسافةَ قبل الفاصلة ويضيفها بعدها.",
    ],
    load: () => import("@/tools/clean-text/tool"),
  }),
  defineTool({
    slug: "find-replace",
    title: "بحث واستبدال",
    titleEn: "Find & Replace",
    description: "دفعةً واحدة، مع التعابير النمطيّة والكلمة الكاملة.",
    category: "docs", subcategory: "cleanup", icon: "swap", version: "1.0.0",
    keywords: ["استبدال", "regex", "تعابير نمطية", "بحث", "كلمة كاملة"],
    keywordsEn: ["find replace", "regex", "substitute"],
    instructions: "اكتب ما تبحث عنه وبديلَه — النتيجةُ تتحدّث فوراً.",
    howItWorks: [
      "بلا خيار «تعبيرٌ نمطيّ» يُعامَل بحثُك نصّاً حرفيّاً، فالرموزُ آمنة.",
      "مع التعبير النمطيّ تعمل المجموعات في البديل: $1 و$2.",
      "«كلمةً كاملة» يمنع مطابقةَ جزءٍ من كلمةٍ أطول.",
    ],
    load: () => import("@/tools/find-replace/tool"),
  }),
  defineTool({
    slug: "sort-lines",
    title: "ترتيب الأسطر",
    titleEn: "Sort Lines",
    description: "فرزٌ عربيٌّ صحيحٌ وعكسٌ وإزالةُ المكرّر.",
    category: "docs", subcategory: "cleanup", icon: "sort", version: "1.0.0",
    keywords: ["فرز", "ترتيب", "مكرر", "قائمة", "أبجدي"],
    keywordsEn: ["sort", "unique", "dedupe"],
    howItWorks: [
      "الفرزُ يستعمل ترتيبَ العربيّة الصحيح لا ترتيبَ الترميز، فالهمزاتُ في مواضعها.",
      "«إزالةُ المكرّر» تُبقي أوّلَ ظهورٍ لكلّ سطر.",
    ],
    load: () => import("@/tools/sort-lines/tool"),
  }),
  defineTool({
    slug: "word-frequency",
    title: "تكرار الكلمات",
    titleEn: "Word Frequency",
    description: "أكثرُ الكلمات ورودًا في نصّ، بجدولٍ قابلٍ للنسخ.",
    category: "docs", subcategory: "analysis", icon: "chart", version: "1.0.0",
    keywords: ["تكرار", "إحصاء", "كلمات مفتاحية", "تحليل نص"],
    keywordsEn: ["word frequency", "term count"],
    howItWorks: [
      "«توحيدُ التشكيل والألف» يجمع «الكتاب» و«الكِتَاب» و«ٱلكتاب» كلمةً واحدة.",
      "يُعرَض أكثرُ ٦٠ كلمة، وزرُّ النسخ يأخذ الجدولَ كاملاً.",
    ],
    load: () => import("@/tools/word-frequency/tool"),
  }),
  defineTool({
    slug: "extract-text",
    title: "استخراج من نصّ",
    titleEn: "Extract from Text",
    description: "بريدٌ وروابطُ وأرقامُ هواتفَ وأرقام، سطراً لكلّ نتيجة.",
    category: "docs", subcategory: "analysis", icon: "filter", version: "1.0.0",
    keywords: ["بريد إلكتروني", "روابط", "أرقام هواتف", "استخراج", "قائمة"],
    keywordsEn: ["extract emails", "extract urls", "phone numbers"],
    howItWorks: [
      "أرقامُ الهواتف تُلتقط بأنماطها الشائعة — راجعها قبل الاعتماد، فالنصُّ الحرّ يخدع.",
      "الأرقامُ العربيّة-الهنديّة تُحوَّل قبل الاستخراج فتُلتقط أيضاً.",
    ],
    load: () => import("@/tools/extract-text/tool"),
  }),
  defineTool({
    slug: "slugify",
    title: "رابط لطيف",
    titleEn: "Slug Generator",
    description: "عنوانٌ عربيٌّ يصير رابطاً نظيفاً — عربيّاً أو منقولاً صوتيّاً.",
    category: "docs", subcategory: "format", icon: "link", version: "1.0.0",
    keywords: ["slug", "رابط", "url", "عنوان", "نقل صوتي", "seo"],
    keywordsEn: ["slug", "url friendly", "transliteration"],
    howItWorks: [
      "الصيغةُ العربيّة تُبقي الحروفَ كما هي — المتصفّحاتُ الحديثة تدعمها وترمّزها عند النسخ.",
      "الصيغةُ اللاتينيّة نقلٌ صوتيٌّ تقريبيّ: أسلمُ للأنظمة القديمة، وأبعدُ عن دقّة النطق.",
    ],
    load: () => import("@/tools/slugify/tool"),
  }),
  defineTool({
    slug: "platform-limits",
    title: "عدّاد حروف المنصّات",
    titleEn: "Platform Character Limits",
    description: "كم بقي لك في إكس ولينكدإن وواتساب والرسائل النصّيّة.",
    category: "docs", subcategory: "analysis", icon: "gauge", version: "1.0.0",
    keywords: ["تويتر", "إكس", "لينكدإن", "واتساب", "sms", "حد الحروف", "منشور"],
    keywordsEn: ["twitter limit", "character limit", "sms length"],
    howItWorks: [
      "العددُ بنقاط الترميز لا بالبايتات — وهو ما تعدّه المنصّات فعلاً.",
      "الرسالةُ النصّيّة العربيّة ٧٠ محرفاً لا ١٦٠، لأنّها تُرسَل بترميز UCS-2.",
    ],
    load: () => import("@/tools/platform-limits/tool"),
  }),
  defineTool({
    slug: "text-diff",
    title: "مقارنة نصّين",
    titleEn: "Text Diff",
    description: "الفروقُ سطراً سطراً، بإضافةٍ وحذفٍ ملوَّنَين.",
    category: "docs", subcategory: "analysis", icon: "diff", version: "1.0.0",
    keywords: ["فروق", "مقارنة", "diff", "نسختان", "تعديلات"],
    keywordsEn: ["diff", "compare text"],
    complexity: "medium",
    howItWorks: [
      "المقارنةُ بأطول تسلسلٍ مشترك — فالأسطرُ المنقولةُ تظهر حذفاً وإضافةً لا تعديلاً.",
      "زرُّ النسخ يعطيك الفروقَ بصيغة + و− المعتادة.",
    ],
    load: () => import("@/tools/text-diff/tool"),
  }),
  defineTool({
    slug: "markdown",
    title: "Markdown إلى HTML",
    titleEn: "Markdown to HTML",
    description: "معاينةٌ حيّةٌ ونسخُ الشيفرة — والنصُّ يُهرَّب فلا يمرّ وسم.",
    category: "docs", subcategory: "format", icon: "markdown", version: "1.0.0",
    keywords: ["markdown", "html", "معاينة", "تنسيق", "نشر"],
    keywordsEn: ["markdown", "html", "preview"],
    complexity: "medium",
    howItWorks: [
      "يدعم العناوينَ والقوائمَ والاقتباسَ والروابطَ والشيفرةَ والخطَّ الفاصل.",
      "كلُّ ما تكتبه يُهرَّب أوّلاً ثمّ يُنسَّق، فلا يمرّ وسمٌ من نصّك إلى الصفحة.",
    ],
    load: () => import("@/tools/markdown/tool"),
  }),

  /* ————— حسابات وأعمال ————— */
  defineTool({
    slug: "number-to-words",
    title: "الأرقام إلى كلمات",
    titleEn: "Number to Words",
    description: "تفقيطُ المبالغ للفواتير والشيكات بالعربيّة والإنكليزيّة — بقواعد العدد الصحيحة.",
    category: "business", subcategory: "invoicing", icon: "numbers", version: "1.0.0",
    keywords: ["تفقيط", "كتابة المبلغ", "شيك", "فاتورة", "ليرة", "دولار", "ريال"],
    keywordsEn: ["number to words", "amount in words", "cheque"],
    complexity: "advanced",
    instructions: "اكتب الرقم واختر العملة — أو «بلا عملة» لقراءةٍ مجرّدة.",
    howItWorks: [
      "يطبّق قواعدَ العدد العربيّة: تمييزَ العدد، ومطابقةَ الجنس المعكوسة في ٣–١٠، والمثنّى.",
      "يراعي صيغَ الإضافة: «مئتا ألف» لا «مئتان ألف»، و«خمسون ألف ليرة» لا «ألفاً ليرة».",
      "يقبل الأرقامَ العربيّة-الهنديّة وفواصلَ الآلاف، حتّى ١٥ خانة.",
    ],
    load: () => import("@/tools/number-to-words/tool"),
  }),
  defineTool({
    slug: "vat",
    title: "ضريبة القيمة المضافة",
    titleEn: "VAT Calculator",
    description: "إضافةً واستخراجاً، بنسبِ البلدان جاهزةً أو نسبةٍ تختارها.",
    category: "business", subcategory: "tax", icon: "receipt", version: "1.0.0",
    keywords: ["ضريبة", "vat", "قيمة مضافة", "شامل الضريبة", "١٥٪", "فاتورة ضريبية"],
    keywordsEn: ["vat", "tax", "inclusive", "exclusive"],
    howItWorks: [
      "استخراجُ الضريبة من مبلغٍ شاملٍ ليس طرحَ النسبة، بل قسمةٌ على (١ + النسبة).",
      "خصمُ ١٥٪ من ١١٥٠ يعطي ٩٧٧٫٥ وهو خطأ؛ الصحيحُ ١٠٠٠.",
    ],
    load: () => import("@/tools/vat/tool"),
  }),
  defineTool({
    slug: "percentage",
    title: "النسبة المئويّة",
    titleEn: "Percentage Calculator",
    description: "ستُّ صيغٍ للسؤال في شاشةٍ واحدة — من الجزء إلى نسبة التغيّر.",
    category: "business", subcategory: "pricing", icon: "percent", version: "1.0.0",
    keywords: ["نسبة", "مئوية", "زيادة", "نقصان", "تغير", "كم بالمئة"],
    keywordsEn: ["percentage", "percent change", "increase"],
    howItWorks: ["الخانتان تتبدّل تسميتُهما بحسب السؤال المختار، فلا تخلط الجزءَ بالكلّ."],
    load: () => import("@/tools/percentage/tool"),
  }),
  defineTool({
    slug: "pricing",
    title: "التسعير والهامش",
    titleEn: "Pricing & Margin",
    description: "من التكلفة إلى سعر البيع — ويفرّق بين الهامش والترميز.",
    category: "business", subcategory: "pricing", icon: "tag", version: "1.0.0",
    keywords: ["هامش", "ربح", "تكلفة", "سعر بيع", "ترميز", "markup", "margin"],
    keywordsEn: ["margin", "markup", "profit", "cost price"],
    complexity: "medium",
    howItWorks: [
      "الهامشُ نسبةٌ من سعر البيع، والترميزُ نسبةٌ من التكلفة — والخلطُ بينهما أشهرُ غلطةِ تسعير.",
      "ترميزُ ٢٥٪ على تكلفة ١٠٠ يعطي هامشاً ٢٠٪ لا ٢٥٪.",
    ],
    load: () => import("@/tools/pricing/tool"),
  }),
  defineTool({
    slug: "discounts",
    title: "الخصومات المتتالية",
    titleEn: "Chained Discounts",
    description: "خصمٌ على خصمٍ — والنسبةُ الفعليّة التي لا تُجمع.",
    category: "business", subcategory: "pricing", icon: "scissors", version: "1.0.0",
    keywords: ["خصم", "تنزيلات", "عروض", "سعر نهائي", "خصم على خصم"],
    keywordsEn: ["discount", "chained discount", "sale price"],
    howItWorks: ["٢٠٪ ثمّ ١٠٪ تساوي ٢٨٪ لا ٣٠٪، لأنّ الخصمَ الثاني يُحسب على ما بقي."],
    load: () => import("@/tools/discounts/tool"),
  }),
  defineTool({
    slug: "timesheet",
    title: "ساعات العمل والأجر",
    titleEn: "Timesheet",
    description: "ورديّاتٌ تُجمع ساعاتُها — وتفهم العابرةَ منتصفَ الليل.",
    category: "business", subcategory: "payroll", icon: "clock", version: "1.0.0",
    keywords: ["دوام", "ساعات", "ورديات", "أجر الساعة", "استراحة"],
    keywordsEn: ["timesheet", "work hours", "shift"],
    complexity: "medium",
    howItWorks: ["الورديّةُ العابرةُ منتصفَ الليل (٢٢:٠٠ ← ٠٦:٠٠) تُحسب ثماني ساعاتٍ لا سالباً."],
    load: () => import("@/tools/timesheet/tool"),
  }),
  defineTool({
    slug: "split-bill",
    title: "تقسيم فاتورة",
    titleEn: "Split the Bill",
    description: "بين أشخاصٍ مع إكراميّة — حصّةُ كلٍّ بالضبط.",
    category: "business", subcategory: "finance", icon: "users", version: "1.0.0",
    keywords: ["تقسيم", "حساب", "مطعم", "إكرامية", "بقشيش", "حصة"],
    keywordsEn: ["split bill", "tip", "share"],
    load: () => import("@/tools/split-bill/tool"),
  }),
  defineTool({
    slug: "iban",
    title: "مدقّق IBAN",
    titleEn: "IBAN Validator",
    description: "تحقّقٌ محلّيٌّ بمعيار mod-97 قبل أن تُرسل حوالةً إلى رقمٍ خاطئ.",
    category: "business", subcategory: "banking", icon: "bank", version: "1.0.0",
    keywords: ["ايبان", "حساب بنكي", "حوالة", "تحقق", "رقم حساب دولي"],
    keywordsEn: ["iban", "bank account", "validate", "mod-97"],
    complexity: "medium",
    howItWorks: [
      "المعيارُ mod-97: تُنقل الأربعةُ الأولى إلى الآخر، وتُبدَّل الحروفُ أرقاماً، فالباقي يجب أن يكون ١.",
      "التحقّقُ يثبت سلامةَ الكتابة لا وجودَ الحساب — فالبنكُ وحده يعرف ذلك.",
      "لا يغادر الرقمُ متصفّحَك.",
    ],
    load: () => import("@/tools/iban/tool"),
  }),
  defineTool({
    slug: "loan",
    title: "جدول سداد قرض",
    titleEn: "Loan Amortization",
    description: "القسطُ الشهريّ وجدولُ الأصل والفائدة شهراً شهراً.",
    category: "business", subcategory: "finance", icon: "loan", version: "1.0.0",
    keywords: ["قرض", "تمويل", "قسط", "فائدة", "جدول سداد", "تمويل عقاري"],
    keywordsEn: ["loan", "amortization", "installment", "interest"],
    complexity: "medium",
    howItWorks: [
      "أقساطٌ ثابتةٌ بطريقة التناقص — الفائدةُ على الرصيد المتبقّي لا على أصل المبلغ.",
      "القسطُ الأخير يبتلع فروقَ التقريب فينتهي الرصيدُ صفراً تماماً.",
    ],
    load: () => import("@/tools/loan/tool"),
  }),
  defineTool({
    slug: "zakat",
    title: "حاسبة الزكاة",
    titleEn: "Zakat Calculator",
    description: "نقدٌ وذهبٌ وفضّةٌ وعروضُ تجارة، بنصابِ الذهب أو الفضّة.",
    category: "business", subcategory: "finance", icon: "crescent", version: "1.0.0",
    keywords: ["زكاة", "نصاب", "ذهب", "فضة", "عروض تجارة", "ربع العشر"],
    keywordsEn: ["zakat", "nisab", "gold", "silver"],
    complexity: "medium",
    howItWorks: [
      "المعدّل ربعُ العشر (٢٫٥٪) على ما بلغ النصابَ وحال عليه الحول.",
      "النصاب ٨٥ غراماً ذهباً أو ٥٩٥ غراماً فضّة — والأخذُ بالفضّة أحوطُ للفقراء.",
      "أسعارُ الغرام تُدخلها بنفسك؛ الحقيبةُ لا تتّصل بمصدرٍ خارجيّ.",
    ],
    load: () => import("@/tools/zakat/tool"),
  }),
  defineTool({
    slug: "end-of-service",
    title: "مكافأة نهاية الخدمة",
    titleEn: "End of Service Benefit",
    description: "تقديرٌ إرشاديٌّ بأنظمة السعوديّة والإمارات أو صيغةٍ تحدّدها.",
    category: "business", subcategory: "payroll", icon: "award", version: "1.0.0",
    keywords: ["نهاية الخدمة", "مكافأة", "استقالة", "تعويض", "عمل"],
    keywordsEn: ["end of service", "gratuity", "severance"],
    complexity: "medium",
    howItWorks: [
      "تقديرٌ إرشاديٌّ لا فتوى قانونيّة — الأنظمةُ تتغيّر.",
      "المستحقُّ يختلف بسبب انتهاء الخدمة (استقالةٌ أم إنهاء) وبما يدخل في «الأجر».",
    ],
    load: () => import("@/tools/end-of-service/tool"),
  }),
  defineTool({
    slug: "invoice",
    title: "فاتورة للطباعة",
    titleEn: "Printable Invoice",
    description: "نموذجٌ عربيٌّ يُملأ ويُطبع أو يُحفظ PDF من المتصفّح.",
    category: "business", subcategory: "invoicing", icon: "receipt", version: "1.0.0",
    printable: true,
    keywords: ["فاتورة", "طباعة", "pdf", "عميل", "بنود", "ضريبة"],
    keywordsEn: ["invoice", "print", "pdf", "billing"],
    complexity: "advanced",
    howItWorks: [
      "المعاينةُ هي نفسُها ما يُطبع — لا مفاجأةَ في الورقة.",
      "الطباعةُ تُخفي حقولَ الإدخال وقشرةَ الموقع، و«حفظ PDF» في نافذة الطباعة يعطيك ملفّاً بلا مكتبةٍ إضافيّة.",
    ],
    load: () => import("@/tools/invoice/tool"),
  }),

  /* ————— تحويلات وقياسات ————— */
  defineTool({
    slug: "hijri-gregorian",
    title: "التقويم الهجريّ والميلاديّ",
    titleEn: "Hijri ↔ Gregorian",
    description: "تحويلٌ في الاتّجاهين مع اسم اليوم — أمّ القرى أو الحسابيّ المدنيّ.",
    category: "convert", subcategory: "datetime", icon: "calendar", version: "1.0.0",
    keywords: ["هجري", "ميلادي", "تقويم", "أم القرى", "تاريخ", "رمضان", "تحويل تاريخ"],
    keywordsEn: ["hijri", "gregorian", "islamic calendar", "umm al-qura"],
    complexity: "advanced",
    howItWorks: [
      "يبني على تقويم المتصفّح المدمج (ICU) — لا مكتبةَ خارجيّةً ولا جداولَ منسوخة.",
      "أمّ القرى والحسابيّ المدنيّ يختلفان بيومٍ في نحو نصف الأشهر — والخيارُ لك.",
      "التقويمُ حسابيٌّ لا رَصْديّ، وقد يفارق رؤيةَ الهلال المحلّيّة يوماً.",
    ],
    load: () => import("@/tools/hijri-gregorian/tool"),
  }),
];

export const registryErrorsAtBoot = TOOLS.length === 0 ? ["السجلّ فارغ"] : [];
