import { defineTool, type ToolManifest } from "@/tools/registry";

export * from "@/tools/registry";
export * from "@/tools/categories";

/**
 * سجلُّ أدوات Do Kits.
 * إضافةُ أداةٍ = عنصرٌ واحدٌ هنا + مجلّدُ `tools/<slug>/`. لا شيءَ آخر.
 */
export const TOOLS: ToolManifest[] = [
  /* ————— نصوص ومستندات ————— */
  defineTool({
    slug: "word-counter",
    title: "عدّاد الكلمات العربيّ",
    titleEn: "Arabic Word Counter",
    description: "كلماتٌ وحروفٌ وجملٌ وزمنُ قراءة — يفهم العربيّةَ وتشكيلَها، ولا يغادر النصُّ متصفّحَك.",
    category: "docs", subcategory: "analysis", icon: "counter", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["عدد الكلمات", "عدد الحروف", "زمن القراءة", "إحصاء", "فقرات", "جمل"],
    keywordsEn: ["word count", "character count", "reading time"],
    instructions: "ألصق نصّك ليُحسَب فوراً — لا يُرسَل شيءٌ إلى الخادم.",
    howItWorks: [
      "الكلمةُ كلُّ تتابعٍ من حروفٍ أو أرقام، فلا تُعدّ علاماتُ الترقيم كلمات.",
      "«بلا تشكيل» يحذف الحركاتِ والتطويلَ قبل العدّ — وهو ما يهمّ عند حساب طول النصّ الفعليّ.",
      "زمنُ القراءة على أساس ١٨٠ كلمةً في الدقيقة، وهو متوسّطُ القراءة العربيّة.",
    ],
    load: () => import("@/tools/word-counter/tool"),
  }),
  defineTool({
    slug: "strip-diacritics",
    title: "إزالة التشكيل",
    titleEn: "Remove Diacritics",
    description: "تجريدُ النصّ من التشكيل والتطويل، وتوحيدُ الألف والتاء للبحث والمطابقة.",
    category: "docs", subcategory: "cleanup", icon: "eraser", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تشكيل", "حركات", "تطويل", "همزة", "توحيد", "بحث", "مطابقة"],
    keywordsEn: ["diacritics", "tashkeel", "normalize arabic"],
    instructions: "اختر ما تريد إزالتَه، وسيُطبَّق على النصّ فوراً.",
    howItWorks: [
      "إزالةُ التشكيل والتطويل لا تمسّ الإملاء — النصُّ يبقى صحيحاً للنشر.",
      "توحيدُ الألف (أ إ آ ← ا) والتاء (ة ← ه) يغيّر الإملاء، فهو للبحث والمطابقة لا للنشر.",
      "المحارفُ الخفيّة تُحذف أيضاً، وهي أشهرُ سببٍ لبحثٍ لا يجد ما تراه العين.",
    ],
    load: () => import("@/tools/strip-diacritics/tool"),
  }),
  defineTool({
    slug: "arabic-numerals",
    title: "تحويل الأرقام",
    titleEn: "Arabic ↔ Latin Numerals",
    description: "بين العربيّة-الهنديّة (٠١٢) واللاتينيّة (012) داخل نصٍّ كامل.",
    category: "docs", subcategory: "format", icon: "digits", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["أرقام عربية", "أرقام هندية", "٠١٢", "تحويل أرقام", "فارسية"],
    keywordsEn: ["arabic numerals", "eastern arabic digits"],
    instructions: "ألصق نصّاً فيه أرقام واختر الاتّجاه.",
    howItWorks: [
      "يبدّل الأرقامَ داخل النصّ ويترك الحروفَ والرموزَ كما هي.",
      "الأرقامُ الفارسيّة (۰۱۲) تُقبل أيضاً وتُحوَّل إلى اللاتينيّة.",
    ],
    load: () => import("@/tools/arabic-numerals/tool"),
  }),
  defineTool({
    slug: "keyboard-fix",
    title: "تصحيح لوحة المفاتيح",
    titleEn: "Keyboard Layout Fixer",
    description: "نصٌّ كُتب والتخطيطُ خاطئ يعود إلى لغته الصحيحة.",
    category: "docs", subcategory: "cleanup", icon: "keyboard", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["لغة خاطئة", "تخطيط", "طلاسم", "معرّب", "كتابة خاطئة", "qwerty"],
    keywordsEn: ["keyboard layout", "wrong language", "transliterate keys"],
    instructions: "ألصق النصّ المبهم — يُخمَّن الاتّجاه تلقائيّاً.",
    howItWorks: [
      "يعتمد تخطيطَ لوحة المفاتيح العربيّة القياسيّة (١٠١) مقابل QWERTY.",
      "الحروفُ المركّبة مثل «لا» و«لأ» تُعامَل مفتاحاً واحداً كما هي في اللوحة.",
      "التخمينُ يقارن عددَ الحروف العربيّة باللاتينيّة، ويمكنك تجاوزُه يدويّاً.",
    ],
    load: () => import("@/tools/keyboard-fix/tool"),
  }),
  defineTool({
    slug: "clean-text",
    title: "تنظيف النصّ",
    titleEn: "Text Cleaner",
    description: "مسافاتٌ زائدةٌ وأسطرٌ فارغةٌ ومحارفُ خفيّةٌ تفسد البحث.",
    category: "docs", subcategory: "cleanup", icon: "broom", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["مسافات", "أسطر فارغة", "محارف خفية", "ترقيم", "تنسيق"],
    keywordsEn: ["clean text", "whitespace", "invisible characters"],
    instructions: "فعّل ما يلزمك من خيارات التنظيف.",
    howItWorks: [
      "«المحارفُ الخفيّة» تشمل الوصلاتِ والعلاماتِ الاتّجاهيّةَ التي لا تُرى وتفسد المطابقة.",
      "«ضبطُ الترقيم» يحذف المسافةَ قبل الفاصلة ويضيفها بعدها.",
    ],
    load: () => import("@/tools/clean-text/tool"),
  }),
  defineTool({
    slug: "find-replace",
    title: "بحث واستبدال",
    titleEn: "Find & Replace",
    description: "دفعةً واحدة، مع التعابير النمطيّة والكلمة الكاملة.",
    category: "docs", subcategory: "cleanup", icon: "swap", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["استبدال", "regex", "تعابير نمطية", "بحث", "كلمة كاملة"],
    keywordsEn: ["find replace", "regex", "substitute"],
    instructions: "اكتب ما تبحث عنه وبديلَه — النتيجةُ تتحدّث فوراً.",
    howItWorks: [
      "بلا خيار «تعبيرٌ نمطيّ» يُعامَل بحثُك نصّاً حرفيّاً، فالرموزُ آمنة.",
      "مع التعبير النمطيّ تعمل المجموعات في البديل: $1 و$2.",
      "«كلمةً كاملة» يمنع مطابقةَ جزءٍ من كلمةٍ أطول.",
    ],
    load: () => import("@/tools/find-replace/tool"),
  }),
  defineTool({
    slug: "sort-lines",
    title: "ترتيب الأسطر",
    titleEn: "Sort Lines",
    description: "فرزٌ عربيٌّ صحيحٌ وعكسٌ وإزالةُ المكرّر.",
    category: "docs", subcategory: "cleanup", icon: "sort", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فرز", "ترتيب", "مكرر", "قائمة", "أبجدي"],
    keywordsEn: ["sort", "unique", "dedupe"],
    howItWorks: [
      "الفرزُ يستعمل ترتيبَ العربيّة الصحيح لا ترتيبَ الترميز، فالهمزاتُ في مواضعها.",
      "«إزالةُ المكرّر» تُبقي أوّلَ ظهورٍ لكلّ سطر.",
    ],
    load: () => import("@/tools/sort-lines/tool"),
  }),
  defineTool({
    slug: "word-frequency",
    title: "تكرار الكلمات",
    titleEn: "Word Frequency",
    description: "أكثرُ الكلمات ورودًا في نصّ، بجدولٍ قابلٍ للنسخ.",
    category: "docs", subcategory: "analysis", icon: "chart", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تكرار", "إحصاء", "كلمات مفتاحية", "تحليل نص"],
    keywordsEn: ["word frequency", "term count"],
    howItWorks: [
      "«توحيدُ التشكيل والألف» يجمع «الكتاب» و«الكِتَاب» و«ٱلكتاب» كلمةً واحدة.",
      "يُعرَض أكثرُ ٦٠ كلمة، وزرُّ النسخ يأخذ الجدولَ كاملاً.",
    ],
    load: () => import("@/tools/word-frequency/tool"),
  }),
  defineTool({
    slug: "extract-text",
    title: "استخراج من نصّ",
    titleEn: "Extract from Text",
    description: "بريدٌ وروابطُ وأرقامُ هواتفَ وأرقام، سطراً لكلّ نتيجة.",
    category: "docs", subcategory: "analysis", icon: "filter", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["بريد إلكتروني", "روابط", "أرقام هواتف", "استخراج", "قائمة"],
    keywordsEn: ["extract emails", "extract urls", "phone numbers"],
    howItWorks: [
      "أرقامُ الهواتف تُلتقط بأنماطها الشائعة — راجعها قبل الاعتماد، فالنصُّ الحرّ يخدع.",
      "الأرقامُ العربيّة-الهنديّة تُحوَّل قبل الاستخراج فتُلتقط أيضاً.",
    ],
    load: () => import("@/tools/extract-text/tool"),
  }),
  defineTool({
    slug: "slugify",
    title: "رابط لطيف",
    titleEn: "Slug Generator",
    description: "عنوانٌ عربيٌّ يصير رابطاً نظيفاً — عربيّاً أو منقولاً صوتيّاً.",
    category: "docs", subcategory: "format", icon: "link", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["slug", "رابط", "url", "عنوان", "نقل صوتي", "seo"],
    keywordsEn: ["slug", "url friendly", "transliteration"],
    howItWorks: [
      "الصيغةُ العربيّة تُبقي الحروفَ كما هي — المتصفّحاتُ الحديثة تدعمها وترمّزها عند النسخ.",
      "الصيغةُ اللاتينيّة نقلٌ صوتيٌّ تقريبيّ: أسلمُ للأنظمة القديمة، وأبعدُ عن دقّة النطق.",
    ],
    load: () => import("@/tools/slugify/tool"),
  }),
  defineTool({
    slug: "platform-limits",
    title: "عدّاد حروف المنصّات",
    titleEn: "Platform Character Limits",
    description: "كم بقي لك في إكس ولينكدإن وواتساب والرسائل النصّيّة.",
    category: "docs", subcategory: "analysis", icon: "gauge", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تويتر", "إكس", "لينكدإن", "واتساب", "sms", "حد الحروف", "منشور"],
    keywordsEn: ["twitter limit", "character limit", "sms length"],
    howItWorks: [
      "العددُ بنقاط الترميز لا بالبايتات — وهو ما تعدّه المنصّات فعلاً.",
      "الرسالةُ النصّيّة العربيّة ٧٠ محرفاً لا ١٦٠، لأنّها تُرسَل بترميز UCS-2.",
    ],
    load: () => import("@/tools/platform-limits/tool"),
  }),
  defineTool({
    slug: "text-diff",
    title: "مقارنة نصّين",
    titleEn: "Text Diff",
    description: "الفروقُ سطراً سطراً، بإضافةٍ وحذفٍ ملوَّنَين.",
    category: "docs", subcategory: "analysis", icon: "diff", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فروق", "مقارنة", "diff", "نسختان", "تعديلات"],
    keywordsEn: ["diff", "compare text"],
    complexity: "medium",
    howItWorks: [
      "المقارنةُ بأطول تسلسلٍ مشترك — فالأسطرُ المنقولةُ تظهر حذفاً وإضافةً لا تعديلاً.",
      "زرُّ النسخ يعطيك الفروقَ بصيغة + و− المعتادة.",
    ],
    load: () => import("@/tools/text-diff/tool"),
  }),
  defineTool({
    slug: "markdown",
    title: "Markdown إلى HTML",
    titleEn: "Markdown to HTML",
    description: "معاينةٌ حيّةٌ ونسخُ الشيفرة — والنصُّ يُهرَّب فلا يمرّ وسم.",
    category: "docs", subcategory: "format", icon: "markdown", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["markdown", "html", "معاينة", "تنسيق", "نشر"],
    keywordsEn: ["markdown", "html", "preview"],
    complexity: "medium",
    howItWorks: [
      "يدعم العناوينَ والقوائمَ والاقتباسَ والروابطَ والشيفرةَ والخطَّ الفاصل.",
      "كلُّ ما تكتبه يُهرَّب أوّلاً ثمّ يُنسَّق، فلا يمرّ وسمٌ من نصّك إلى الصفحة.",
    ],
    load: () => import("@/tools/markdown/tool"),
  }),

  /* ————— حسابات وأعمال ————— */
  defineTool({
    slug: "number-to-words",
    title: "الأرقام إلى كلمات",
    titleEn: "Number to Words",
    description: "تفقيطُ المبالغ للفواتير والشيكات بالعربيّة والإنكليزيّة — بقواعد العدد الصحيحة.",
    category: "business", subcategory: "invoicing", icon: "numbers", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تفقيط", "كتابة المبلغ", "شيك", "فاتورة", "ليرة", "دولار", "ريال"],
    keywordsEn: ["number to words", "amount in words", "cheque"],
    complexity: "advanced",
    instructions: "اكتب الرقم واختر العملة — أو «بلا عملة» لقراءةٍ مجرّدة.",
    howItWorks: [
      "يطبّق قواعدَ العدد العربيّة: تمييزَ العدد، ومطابقةَ الجنس المعكوسة في ٣–١٠، والمثنّى.",
      "يراعي صيغَ الإضافة: «مئتا ألف» لا «مئتان ألف»، و«خمسون ألف ليرة» لا «ألفاً ليرة».",
      "يقبل الأرقامَ العربيّة-الهنديّة وفواصلَ الآلاف، حتّى ١٥ خانة.",
    ],
    load: () => import("@/tools/number-to-words/tool"),
  }),
  defineTool({
    slug: "vat",
    title: "ضريبة القيمة المضافة",
    titleEn: "VAT Calculator",
    description: "إضافةً واستخراجاً، بنسبِ البلدان جاهزةً أو نسبةٍ تختارها.",
    category: "business", subcategory: "tax", icon: "receipt", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ضريبة", "vat", "قيمة مضافة", "شامل الضريبة", "١٥٪", "فاتورة ضريبية"],
    keywordsEn: ["vat", "tax", "inclusive", "exclusive"],
    howItWorks: [
      "استخراجُ الضريبة من مبلغٍ شاملٍ ليس طرحَ النسبة، بل قسمةٌ على (١ + النسبة).",
      "خصمُ ١٥٪ من ١١٥٠ يعطي ٩٧٧٫٥ وهو خطأ؛ الصحيحُ ١٠٠٠.",
    ],
    load: () => import("@/tools/vat/tool"),
  }),
  defineTool({
    slug: "percentage",
    title: "النسبة المئويّة",
    titleEn: "Percentage Calculator",
    description: "ستُّ صيغٍ للسؤال في شاشةٍ واحدة — من الجزء إلى نسبة التغيّر.",
    category: "business", subcategory: "pricing", icon: "percent", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["نسبة", "مئوية", "زيادة", "نقصان", "تغير", "كم بالمئة"],
    keywordsEn: ["percentage", "percent change", "increase"],
    howItWorks: ["الخانتان تتبدّل تسميتُهما بحسب السؤال المختار، فلا تخلط الجزءَ بالكلّ."],
    load: () => import("@/tools/percentage/tool"),
  }),
  defineTool({
    slug: "pricing",
    title: "التسعير والهامش",
    titleEn: "Pricing & Margin",
    description: "من التكلفة إلى سعر البيع — ويفرّق بين الهامش والترميز.",
    category: "business", subcategory: "pricing", icon: "tag", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["هامش", "ربح", "تكلفة", "سعر بيع", "ترميز", "markup", "margin"],
    keywordsEn: ["margin", "markup", "profit", "cost price"],
    complexity: "medium",
    howItWorks: [
      "الهامشُ نسبةٌ من سعر البيع، والترميزُ نسبةٌ من التكلفة — والخلطُ بينهما أشهرُ غلطةِ تسعير.",
      "ترميزُ ٢٥٪ على تكلفة ١٠٠ يعطي هامشاً ٢٠٪ لا ٢٥٪.",
    ],
    load: () => import("@/tools/pricing/tool"),
  }),
  defineTool({
    slug: "discounts",
    title: "الخصومات المتتالية",
    titleEn: "Chained Discounts",
    description: "خصمٌ على خصمٍ — والنسبةُ الفعليّة التي لا تُجمع.",
    category: "business", subcategory: "pricing", icon: "scissors", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["خصم", "تنزيلات", "عروض", "سعر نهائي", "خصم على خصم"],
    keywordsEn: ["discount", "chained discount", "sale price"],
    howItWorks: ["٢٠٪ ثمّ ١٠٪ تساوي ٢٨٪ لا ٣٠٪، لأنّ الخصمَ الثاني يُحسب على ما بقي."],
    load: () => import("@/tools/discounts/tool"),
  }),
  defineTool({
    slug: "timesheet",
    title: "ساعات العمل والأجر",
    titleEn: "Timesheet",
    description: "ورديّاتٌ تُجمع ساعاتُها — وتفهم العابرةَ منتصفَ الليل.",
    category: "business", subcategory: "payroll", icon: "clock", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["دوام", "ساعات", "ورديات", "أجر الساعة", "استراحة"],
    keywordsEn: ["timesheet", "work hours", "shift"],
    complexity: "medium",
    howItWorks: ["الورديّةُ العابرةُ منتصفَ الليل (٢٢:٠٠ ← ٠٦:٠٠) تُحسب ثماني ساعاتٍ لا سالباً."],
    load: () => import("@/tools/timesheet/tool"),
  }),
  defineTool({
    slug: "split-bill",
    title: "تقسيم فاتورة",
    titleEn: "Split the Bill",
    description: "بين أشخاصٍ مع إكراميّة — حصّةُ كلٍّ بالضبط.",
    category: "business", subcategory: "finance", icon: "users", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تقسيم", "حساب", "مطعم", "إكرامية", "بقشيش", "حصة"],
    keywordsEn: ["split bill", "tip", "share"],
    load: () => import("@/tools/split-bill/tool"),
  }),
  defineTool({
    slug: "iban",
    title: "مدقّق IBAN",
    titleEn: "IBAN Validator",
    description: "تحقّقٌ محلّيٌّ بمعيار mod-97 قبل أن تُرسل حوالةً إلى رقمٍ خاطئ.",
    category: "business", subcategory: "banking", icon: "bank", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ايبان", "حساب بنكي", "حوالة", "تحقق", "رقم حساب دولي"],
    keywordsEn: ["iban", "bank account", "validate", "mod-97"],
    complexity: "medium",
    howItWorks: [
      "المعيارُ mod-97: تُنقل الأربعةُ الأولى إلى الآخر، وتُبدَّل الحروفُ أرقاماً، فالباقي يجب أن يكون ١.",
      "التحقّقُ يثبت سلامةَ الكتابة لا وجودَ الحساب — فالبنكُ وحده يعرف ذلك.",
      "لا يغادر الرقمُ متصفّحَك.",
    ],
    load: () => import("@/tools/iban/tool"),
  }),
  defineTool({
    slug: "loan",
    title: "جدول سداد قرض",
    titleEn: "Loan Amortization",
    description: "القسطُ الشهريّ وجدولُ الأصل والفائدة شهراً شهراً.",
    category: "business", subcategory: "finance", icon: "loan", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["قرض", "تمويل", "قسط", "فائدة", "جدول سداد", "تمويل عقاري"],
    keywordsEn: ["loan", "amortization", "installment", "interest"],
    complexity: "medium",
    howItWorks: [
      "أقساطٌ ثابتةٌ بطريقة التناقص — الفائدةُ على الرصيد المتبقّي لا على أصل المبلغ.",
      "القسطُ الأخير يبتلع فروقَ التقريب فينتهي الرصيدُ صفراً تماماً.",
    ],
    load: () => import("@/tools/loan/tool"),
  }),
  defineTool({
    slug: "zakat",
    title: "حاسبة الزكاة",
    titleEn: "Zakat Calculator",
    description: "نقدٌ وذهبٌ وفضّةٌ وعروضُ تجارة، بنصابِ الذهب أو الفضّة.",
    category: "business", subcategory: "finance", icon: "crescent", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["زكاة", "نصاب", "ذهب", "فضة", "عروض تجارة", "ربع العشر"],
    keywordsEn: ["zakat", "nisab", "gold", "silver"],
    complexity: "medium",
    howItWorks: [
      "المعدّل ربعُ العشر (٢٫٥٪) على ما بلغ النصابَ وحال عليه الحول.",
      "النصاب ٨٥ غراماً ذهباً أو ٥٩٥ غراماً فضّة — والأخذُ بالفضّة أحوطُ للفقراء.",
      "أسعارُ الغرام تُدخلها بنفسك؛ الحقيبةُ لا تتّصل بمصدرٍ خارجيّ.",
    ],
    load: () => import("@/tools/zakat/tool"),
  }),
  defineTool({
    slug: "end-of-service",
    title: "مكافأة نهاية الخدمة",
    titleEn: "End of Service Benefit",
    description: "تقديرٌ إرشاديٌّ بأنظمة السعوديّة والإمارات أو صيغةٍ تحدّدها.",
    category: "business", subcategory: "payroll", icon: "award", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["نهاية الخدمة", "مكافأة", "استقالة", "تعويض", "عمل"],
    keywordsEn: ["end of service", "gratuity", "severance"],
    complexity: "medium",
    howItWorks: [
      "تقديرٌ إرشاديٌّ لا فتوى قانونيّة — الأنظمةُ تتغيّر.",
      "المستحقُّ يختلف بسبب انتهاء الخدمة (استقالةٌ أم إنهاء) وبما يدخل في «الأجر».",
    ],
    load: () => import("@/tools/end-of-service/tool"),
  }),
  defineTool({
    slug: "invoice",
    title: "فاتورة للطباعة",
    titleEn: "Printable Invoice",
    description: "نموذجٌ عربيٌّ يُملأ ويُطبع أو يُحفظ PDF من المتصفّح.",
    category: "business", subcategory: "invoicing", icon: "receipt", version: "1.0.0", publishedAt: "2026-08-30",
    capabilities: { print: true, exportPdf: true, exportCsv: true, saveDraft: true },
    keywords: ["فاتورة", "طباعة", "pdf", "عميل", "بنود", "ضريبة"],
    keywordsEn: ["invoice", "print", "pdf", "billing"],
    complexity: "advanced",
    howItWorks: [
      "المعاينةُ هي نفسُها ما يُطبع — لا مفاجأةَ في الورقة.",
      "الطباعةُ تُخفي حقولَ الإدخال وقشرةَ الموقع، و«حفظ PDF» في نافذة الطباعة يعطيك ملفّاً بلا مكتبةٍ إضافيّة.",
    ],
    load: () => import("@/tools/invoice/tool"),
  }),

  /* ————— تحويلات وقياسات ————— */
  defineTool({
    slug: "hijri-gregorian",
    title: "التقويم الهجريّ والميلاديّ",
    titleEn: "Hijri ↔ Gregorian",
    description: "تحويلٌ في الاتّجاهين مع اسم اليوم — أمّ القرى أو الحسابيّ المدنيّ.",
    category: "convert", subcategory: "datetime", icon: "calendar", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["هجري", "ميلادي", "تقويم", "أم القرى", "تاريخ", "رمضان", "تحويل تاريخ"],
    keywordsEn: ["hijri", "gregorian", "islamic calendar", "umm al-qura"],
    complexity: "advanced",
    howItWorks: [
      "يبني على تقويم المتصفّح المدمج (ICU) — لا مكتبةَ خارجيّةً ولا جداولَ منسوخة.",
      "أمّ القرى والحسابيّ المدنيّ يختلفان بيومٍ في نحو نصف الأشهر — والخيارُ لك.",
      "التقويمُ حسابيٌّ لا رَصْديّ، وقد يفارق رؤيةَ الهلال المحلّيّة يوماً.",
    ],
    load: () => import("@/tools/hijri-gregorian/tool"),
  }),

  defineTool({
    slug: "units",
    title: "محوّل الوحدات",
    titleEn: "Unit Converter",
    description: "طولٌ ووزنٌ وحجمٌ ومساحةٌ وسرعةٌ وزمنٌ وحرارة — بجدولٍ يعرض كلَّ الوحدات معاً.",
    category: "convert", subcategory: "units", icon: "ruler", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["وحدات", "تحويل", "متر", "قدم", "كيلو", "رطل", "لتر", "مئوي", "فهرنهايت", "ميل"],
    keywordsEn: ["unit converter", "metric", "imperial", "celsius", "fahrenheit"],
    complexity: "medium",
    instructions: "اختر النوعَ ثمّ الوحدتين — والجدولُ أسفلَه يعطيك القيمةَ بكلّ الوحدات دفعةً واحدة.",
    howItWorks: [
      "كلُّ وحدةٍ لها معاملٌ إلى وحدةٍ أساسٍ، والتحويلُ ضربٌ وقسمة — فلا يتراكم خطأُ التقريب.",
      "الحرارةُ ليست نسبيّةً كالطول (صفرُها ليس عدماً)، فلها مسارُ تحويلٍ خاصٌّ ونوعٌ مستقلّ.",
    ],
    load: () => import("@/tools/units/tool"),
  }),
  defineTool({
    slug: "date-diff",
    title: "الفرق بين تاريخين",
    titleEn: "Date Difference",
    description: "بالسنين والأشهر والأيّام معاً، ومجموعِ الأيّام والأسابيع.",
    category: "convert", subcategory: "datetime", icon: "calendarDiff", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فرق تاريخين", "مدة", "كم يوم", "حساب المدة", "عقد", "مدة العقد"],
    keywordsEn: ["date difference", "days between", "duration"],
    howItWorks: [
      "الأشهرُ تُعدّ بالتقويم لا بمتوسّطٍ ثابت: نأخذ أكبرَ عددِ أشهرٍ يبقى ضمن المدّة ثمّ نعدّ الأيّامَ الباقية.",
      "«٣١ كانون الثاني + شهر» تساوي آخرَ شباط بالقصّ — فالمدّةُ بينهما شهرٌ تامّ لا ناقص.",
    ],
    load: () => import("@/tools/date-diff/tool"),
  }),
  defineTool({
    slug: "age",
    title: "حاسبة العمر",
    titleEn: "Age Calculator",
    description: "عمرُك بالسنين والأشهر والأيّام، ويومُ ميلادك، وموعدُ ميلادك القادم.",
    category: "convert", subcategory: "datetime", icon: "cake", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["العمر", "كم عمري", "تاريخ الميلاد", "عيد ميلاد", "سنّ"],
    keywordsEn: ["age calculator", "birthday", "how old"],
    howItWorks: [
      "الحسابُ تقويميٌّ لا بمتوسّط، فالسنواتُ الكبيسةُ محسوبةٌ على حقيقتها.",
      "يومُ الميلاد يُشتقّ من التاريخ نفسه — لا حاجةَ إلى جدول.",
    ],
    load: () => import("@/tools/age/tool"),
  }),
  defineTool({
    slug: "business-days",
    title: "أيّام العمل",
    titleEn: "Business Days",
    description: "أيّامُ العمل بين تاريخين مع اختيار عطلة الأسبوع وطرحِ العطل الرسميّة.",
    category: "convert", subcategory: "datetime", icon: "briefcase", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["أيام عمل", "دوام", "عطلة", "مدة تسليم", "أيام عمل فعلية"],
    keywordsEn: ["business days", "working days", "weekend"],
    complexity: "medium",
    howItWorks: [
      "عطلةُ الأسبوع تختلف بين البلدان — الجمعةُ والسبت في أكثر البلاد العربيّة، والسبتُ والأحد في غيرها.",
      "العطلةُ الرسميّةُ التي تصادف نهايةَ الأسبوع لا تُطرح مرّتين.",
      "الطرفان محسوبان ضمن المدّة.",
    ],
    load: () => import("@/tools/business-days/tool"),
  }),
  defineTool({
    slug: "timezones",
    title: "المناطق الزمنيّة",
    titleEn: "Time Zones",
    description: "كم الساعةُ هناك — مع جدولٍ يعرض اللحظةَ نفسَها في مدنٍ كثيرة.",
    category: "convert", subcategory: "datetime", icon: "globe", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["توقيت", "فرق التوقيت", "مناطق زمنية", "اجتماع", "كم الساعة", "توقيت صيفي"],
    keywordsEn: ["timezone", "time difference", "meeting time"],
    complexity: "medium",
    howItWorks: [
      "الإزاحاتُ يحسبها متصفّحك بجدول المناطق المدمج، فيراعي التوقيتَ الصيفيّ في تاريخ سؤالك لا في تاريخ اليوم.",
      "لذلك يتغيّر الفرقُ بين مدينتين بحسب الشهر — وهذا صحيحٌ لا خطأ.",
    ],
    load: () => import("@/tools/timezones/tool"),
  }),
  defineTool({
    slug: "file-size",
    title: "حجوم الملفّات",
    titleEn: "File Size Converter",
    description: "بايتٌ وكيلوٌ وميغا وغيغا — وبالأساسين ١٠٠٠ و١٠٢٤ معاً.",
    category: "convert", subcategory: "units", icon: "drive", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["حجم ملف", "ميغابايت", "غيغابايت", "بايت", "سعة", "قرص"],
    keywordsEn: ["file size", "megabyte", "gigabyte", "bytes"],
    howItWorks: [
      "الأساس ١٠٢٤ ما يعرضه نظامُ التشغيل، والأساس ١٠٠٠ ما يكتبه صنّاعُ الأقراص.",
      "لذلك يبدو قرصُ «١ تيرابايت» ٩٣١ غيبيبايت بعد التركيب — والفرقُ ليس عطلاً.",
    ],
    load: () => import("@/tools/file-size/tool"),
  }),
  defineTool({
    slug: "number-base",
    title: "أنظمة العدّ",
    titleEn: "Number Base Converter",
    description: "ثنائيٌّ وثمانيٌّ وعشريٌّ وستّ عشريّ — بأعدادٍ كبيرةٍ بلا فقدِ دقّة.",
    category: "convert", subcategory: "numbers", icon: "binary", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ثنائي", "hex", "ست عشري", "binary", "أساس", "تحويل أنظمة"],
    keywordsEn: ["binary", "hexadecimal", "base converter"],
    howItWorks: [
      "الحسابُ بأعدادٍ صحيحةٍ غيرِ محدودة (BigInt)، فالأعدادُ الكبيرةُ تُحوَّل بلا تقريب.",
      "المحرفُ غيرُ المسموح في الأساس يُكشف باسمه بدل نتيجةٍ خاطئةٍ صامتة.",
    ],
    load: () => import("@/tools/number-base/tool"),
  }),
  defineTool({
    slug: "coordinates",
    title: "تحويل الإحداثيّات",
    titleEn: "Coordinate Converter",
    description: "درجاتٌ عشريّة ↔ درجة ودقيقة وثانية، في الاتّجاهين.",
    category: "convert", subcategory: "units", icon: "pin", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["إحداثيات", "خط طول", "خط عرض", "gps", "خرائط", "درجة دقيقة ثانية"],
    keywordsEn: ["coordinates", "dms", "latitude", "longitude", "gps"],
    complexity: "medium",
    howItWorks: [
      "الصيغةُ العشريّةُ ما تقبله الخرائطُ عادةً، والدرجاتُ والدقائقُ والثواني ما تجده في الوثائق المساحيّة.",
      "السالبُ جنوباً وغرباً — والأداةُ ترفض ما يتجاوز حدودَ الكرة.",
    ],
    load: () => import("@/tools/coordinates/tool"),
  }),
  defineTool({
    slug: "clothing-sizes",
    title: "مقاسات الملابس والأحذية",
    titleEn: "Clothing & Shoe Sizes",
    description: "جداولُ أوروبا وبريطانيا وأمريكا للملابس والأحذية، رجاليّةً ونسائيّة.",
    category: "convert", subcategory: "units", icon: "shirt", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["مقاسات", "أحذية", "ملابس", "تسوق", "شراء اونلاين", "مقاس أوروبي"],
    keywordsEn: ["size chart", "shoe size", "clothing size"],
    howItWorks: [
      "الجداولُ إرشاديّة: المقاساتُ تختلف بين العلامات التجاريّة اختلافاً حقيقيّاً.",
      "للأحذية قِس طولَ قدمك بالسنتيمتر — فهو أدقُّ من أيّ رقمِ مقاس.",
    ],
    load: () => import("@/tools/clothing-sizes/tool"),
  }),
  defineTool({
    slug: "prayer-times",
    title: "مواقيت الصلاة",
    titleEn: "Prayer Times",
    description: "حسابٌ فلكيٌّ في متصفّحك بستّ طرقٍ ومذهبَي العصر — بلا إنترنتٍ ولا تتبّعِ موقع.",
    category: "convert", subcategory: "datetime", icon: "mosque", version: "1.0.0", publishedAt: "2026-08-30",
    status: "beta",
    complexity: "advanced",
    keywords: ["مواقيت الصلاة", "أذان", "الفجر", "المغرب", "العشاء", "القبلة", "أم القرى", "شروق"],
    keywordsEn: ["prayer times", "salah", "adhan", "fajr", "maghrib"],
    tags: ["حسابٌ فلكيّ", "تجريبيّة"],
    instructions: "اختر مدينتك أو أدخل إحداثيّاتٍ — لا يُطلب موقعُك ولا يُرسَل شيء.",
    howItWorks: [
      "الحسابُ فلكيٌّ قياسيّ: موضعُ الشمس (الميلُ ومعادلةُ الزمن) ثمّ زاويةُ الساعة لكلّ ارتفاعٍ مطلوب.",
      "الطرقُ تختلف في زاويتَي الفجر والعشاء، وأمّ القرى تجعل العشاءَ بعد المغرب بتسعين دقيقة.",
      "العصرُ عند الجمهور حين يصير ظلُّ الشيء مثلَه، وعند الحنفيّة مثلَيه.",
      "تحقّقٌ داخليّ: الظهرُ يطابق منتصفَ ما بين الشروق والغروب، وطولُ النهار يطابق القيمَ المعروفة.",
      "الأشهرُ الرسميّةُ قد تفارقه دقائقَ لاختلاف الطريقة أو الاحتياط — اعتمد إعلانَ بلدك.",
    ],
    faq: [
      { q: "لماذا تختلف عن تقويم بلدي بدقيقة أو دقيقتين؟",
        a: "لأنّ الهيئاتِ تختلف في الزوايا وفي التقريب والاحتياط. جرّب تبديلَ طريقة الحساب لتقترب من تقويمك، والفرقُ الباقي مقصودٌ عندهم غالباً." },
      { q: "هل يُرسَل موقعي؟",
        a: "لا. الحسابُ كلُّه في متصفّحك، والمدنُ جدولٌ مخزَّنٌ في الأداة. وإن أدخلتَ إحداثيّاتٍ فهي تبقى عندك." },
      { q: "لماذا الأداةُ موسومةٌ «تجريبيّة»؟",
        a: "لأنّ الحسابَ الفلكيَّ مُتحقَّقٌ منه داخليّاً لكنّه لم يُقارَن بعدُ بتقاويم كلّ البلدان. استعمله للتقدير والتخطيط، واعتمد إعلانَ بلدك للصلاة." },
    ],
    load: () => import("@/tools/prayer-times/tool"),
  }),
];

export const registryErrorsAtBoot = TOOLS.length === 0 ? ["السجلّ فارغ"] : [];
