import { defineTool, type ToolManifest } from "@/tools/registry";

export * from "@/tools/registry";
export * from "@/tools/categories";

/**
 * سجلُّ أدوات Do Kits.
 * إضافةُ أداةٍ = عنصرٌ واحدٌ هنا + مجلّدُ `tools/<slug>/`. لا شيءَ آخر.
 */
export const TOOLS: ToolManifest[] = [
  /* ————— نصوص ومستندات ————— */
  defineTool({
    slug: "word-counter",
    title: "عدّاد الكلمات العربيّ",
    titleEn: "Arabic Word Counter",
    description: "كلماتٌ وحروفٌ وجملٌ وزمنُ قراءة — يفهم العربيّةَ وتشكيلَها، ولا يغادر النصُّ متصفّحَك.",
    category: "docs", subcategory: "analysis", icon: "counter", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["عدد الكلمات", "عدد الحروف", "زمن القراءة", "إحصاء", "فقرات", "جمل"],
    keywordsEn: ["word count", "character count", "reading time"],
    instructions: "ألصق نصّك ليُحسَب فوراً — لا يُرسَل شيءٌ إلى الخادم.",
    howItWorks: [
      "الكلمةُ كلُّ تتابعٍ من حروفٍ أو أرقام، فلا تُعدّ علاماتُ الترقيم كلمات.",
      "«بلا تشكيل» يحذف الحركاتِ والتطويلَ قبل العدّ — وهو ما يهمّ عند حساب طول النصّ الفعليّ.",
      "زمنُ القراءة على أساس ١٨٠ كلمةً في الدقيقة، وهو متوسّطُ القراءة العربيّة.",
    ],
    nextSteps: [
      { slug: "clean-text", label: "نظّف هذا النصّ", labelEn: "Clean up this text" },
      { slug: "word-frequency", label: "اعرف أكثرَ كلماته وروداً", labelEn: "See its most frequent words" },
    ],
    load: () => import("@/tools/word-counter/tool"),
  }),
  defineTool({
    slug: "strip-diacritics",
    title: "إزالة التشكيل",
    titleEn: "Remove Diacritics",
    description: "تجريدُ النصّ من التشكيل والتطويل، وتوحيدُ الألف والتاء للبحث والمطابقة.",
    category: "docs", subcategory: "cleanup", icon: "eraser", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تشكيل", "حركات", "تطويل", "همزة", "توحيد", "بحث", "مطابقة"],
    keywordsEn: ["diacritics", "tashkeel", "normalize arabic"],
    instructions: "اختر ما تريد إزالتَه، وسيُطبَّق على النصّ فوراً.",
    howItWorks: [
      "إزالةُ التشكيل والتطويل لا تمسّ الإملاء — النصُّ يبقى صحيحاً للنشر.",
      "توحيدُ الألف (أ إ آ ← ا) والتاء (ة ← ه) يغيّر الإملاء، فهو للبحث والمطابقة لا للنشر.",
      "المحارفُ الخفيّة تُحذف أيضاً، وهي أشهرُ سببٍ لبحثٍ لا يجد ما تراه العين.",
    ],
    load: () => import("@/tools/strip-diacritics/tool"),
  }),
  defineTool({
    slug: "arabic-numerals",
    title: "تحويل الأرقام",
    titleEn: "Arabic ↔ Latin Numerals",
    description: "بين العربيّة-الهنديّة (٠١٢) واللاتينيّة (012) داخل نصٍّ كامل.",
    category: "docs", subcategory: "format", icon: "digits", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["أرقام عربية", "أرقام هندية", "٠١٢", "تحويل أرقام", "فارسية"],
    keywordsEn: ["arabic numerals", "eastern arabic digits"],
    instructions: "ألصق نصّاً فيه أرقام واختر الاتّجاه.",
    howItWorks: [
      "يبدّل الأرقامَ داخل النصّ ويترك الحروفَ والرموزَ كما هي.",
      "الأرقامُ الفارسيّة (۰۱۲) تُقبل أيضاً وتُحوَّل إلى اللاتينيّة.",
    ],
    load: () => import("@/tools/arabic-numerals/tool"),
  }),
  defineTool({
    slug: "keyboard-fix",
    title: "تصحيح لوحة المفاتيح",
    titleEn: "Keyboard Layout Fixer",
    description: "نصٌّ كُتب والتخطيطُ خاطئ يعود إلى لغته الصحيحة.",
    category: "docs", subcategory: "cleanup", icon: "keyboard", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["لغة خاطئة", "تخطيط", "طلاسم", "معرّب", "كتابة خاطئة", "qwerty"],
    keywordsEn: ["keyboard layout", "wrong language", "transliterate keys"],
    instructions: "ألصق النصّ المبهم — يُخمَّن الاتّجاه تلقائيّاً.",
    howItWorks: [
      "يعتمد تخطيطَ لوحة المفاتيح العربيّة القياسيّة (١٠١) مقابل QWERTY.",
      "الحروفُ المركّبة مثل «لا» و«لأ» تُعامَل مفتاحاً واحداً كما هي في اللوحة.",
      "التخمينُ يقارن عددَ الحروف العربيّة باللاتينيّة، ويمكنك تجاوزُه يدويّاً.",
    ],
    load: () => import("@/tools/keyboard-fix/tool"),
  }),
  defineTool({
    slug: "clean-text",
    title: "تنظيف النصّ",
    titleEn: "Text Cleaner",
    description: "مسافاتٌ زائدةٌ وأسطرٌ فارغةٌ ومحارفُ خفيّةٌ تفسد البحث.",
    category: "docs", subcategory: "cleanup", icon: "broom", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["مسافات", "أسطر فارغة", "محارف خفية", "ترقيم", "تنسيق"],
    keywordsEn: ["clean text", "whitespace", "invisible characters"],
    instructions: "فعّل ما يلزمك من خيارات التنظيف.",
    howItWorks: [
      "«المحارفُ الخفيّة» تشمل الوصلاتِ والعلاماتِ الاتّجاهيّةَ التي لا تُرى وتفسد المطابقة.",
      "«ضبطُ الترقيم» يحذف المسافةَ قبل الفاصلة ويضيفها بعدها.",
    ],
    nextSteps: [
      { slug: "strip-diacritics", label: "جرّده من التشكيل", labelEn: "Strip its diacritics" },
      { slug: "unicode-inspect", label: "افحص ما بقي فيه من محارفَ خفيّة", labelEn: "Inspect it for invisible characters" },
    ],
    load: () => import("@/tools/clean-text/tool"),
  }),
  defineTool({
    slug: "find-replace",
    title: "بحث واستبدال",
    titleEn: "Find & Replace",
    description: "دفعةً واحدة، مع التعابير النمطيّة والكلمة الكاملة.",
    category: "docs", subcategory: "cleanup", icon: "swap", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["استبدال", "regex", "تعابير نمطية", "بحث", "كلمة كاملة"],
    keywordsEn: ["find replace", "regex", "substitute"],
    instructions: "اكتب ما تبحث عنه وبديلَه — النتيجةُ تتحدّث فوراً.",
    howItWorks: [
      "بلا خيار «تعبيرٌ نمطيّ» يُعامَل بحثُك نصّاً حرفيّاً، فالرموزُ آمنة.",
      "مع التعبير النمطيّ تعمل المجموعات في البديل: $1 و$2.",
      "«كلمةً كاملة» يمنع مطابقةَ جزءٍ من كلمةٍ أطول.",
    ],
    load: () => import("@/tools/find-replace/tool"),
  }),
  defineTool({
    slug: "sort-lines",
    title: "ترتيب الأسطر",
    titleEn: "Sort Lines",
    description: "فرزٌ عربيٌّ صحيحٌ وعكسٌ وإزالةُ المكرّر.",
    category: "docs", subcategory: "cleanup", icon: "sort", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فرز", "ترتيب", "مكرر", "قائمة", "أبجدي"],
    keywordsEn: ["sort", "unique", "dedupe"],
    howItWorks: [
      "الفرزُ يستعمل ترتيبَ العربيّة الصحيح لا ترتيبَ الترميز، فالهمزاتُ في مواضعها.",
      "«إزالةُ المكرّر» تُبقي أوّلَ ظهورٍ لكلّ سطر.",
    ],
    load: () => import("@/tools/sort-lines/tool"),
  }),
  defineTool({
    slug: "word-frequency",
    title: "تكرار الكلمات",
    titleEn: "Word Frequency",
    description: "أكثرُ الكلمات ورودًا في نصّ، بجدولٍ قابلٍ للنسخ.",
    category: "docs", subcategory: "analysis", icon: "chart", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تكرار", "إحصاء", "كلمات مفتاحية", "تحليل نص"],
    keywordsEn: ["word frequency", "term count"],
    howItWorks: [
      "«توحيدُ التشكيل والألف» يجمع «الكتاب» و«الكِتَاب» و«ٱلكتاب» كلمةً واحدة.",
      "يُعرَض أكثرُ ٦٠ كلمة، وزرُّ النسخ يأخذ الجدولَ كاملاً.",
    ],
    load: () => import("@/tools/word-frequency/tool"),
  }),
  defineTool({
    slug: "extract-text",
    title: "استخراج من نصّ",
    titleEn: "Extract from Text",
    description: "بريدٌ وروابطُ وأرقامُ هواتفَ وأرقام، سطراً لكلّ نتيجة.",
    category: "docs", subcategory: "analysis", icon: "filter", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["بريد إلكتروني", "روابط", "أرقام هواتف", "استخراج", "قائمة"],
    keywordsEn: ["extract emails", "extract urls", "phone numbers"],
    howItWorks: [
      "أرقامُ الهواتف تُلتقط بأنماطها الشائعة — راجعها قبل الاعتماد، فالنصُّ الحرّ يخدع.",
      "الأرقامُ العربيّة-الهنديّة تُحوَّل قبل الاستخراج فتُلتقط أيضاً.",
    ],
    load: () => import("@/tools/extract-text/tool"),
  }),
  defineTool({
    slug: "slugify",
    title: "رابط لطيف",
    titleEn: "Slug Generator",
    description: "عنوانٌ عربيٌّ يصير رابطاً نظيفاً — عربيّاً أو منقولاً صوتيّاً.",
    category: "docs", subcategory: "format", icon: "link", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["slug", "رابط", "url", "عنوان", "نقل صوتي", "seo"],
    keywordsEn: ["slug", "url friendly", "transliteration"],
    howItWorks: [
      "الصيغةُ العربيّة تُبقي الحروفَ كما هي — المتصفّحاتُ الحديثة تدعمها وترمّزها عند النسخ.",
      "الصيغةُ اللاتينيّة نقلٌ صوتيٌّ تقريبيّ: أسلمُ للأنظمة القديمة، وأبعدُ عن دقّة النطق.",
    ],
    load: () => import("@/tools/slugify/tool"),
  }),
  defineTool({
    slug: "platform-limits",
    title: "عدّاد حروف المنصّات",
    titleEn: "Platform Character Limits",
    description: "كم بقي لك في إكس ولينكدإن وواتساب والرسائل النصّيّة.",
    category: "docs", subcategory: "analysis", icon: "gauge", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تويتر", "إكس", "لينكدإن", "واتساب", "sms", "حد الحروف", "منشور"],
    keywordsEn: ["twitter limit", "character limit", "sms length"],
    howItWorks: [
      "العددُ بنقاط الترميز لا بالبايتات — وهو ما تعدّه المنصّات فعلاً.",
      "الرسالةُ النصّيّة العربيّة ٧٠ محرفاً لا ١٦٠، لأنّها تُرسَل بترميز UCS-2.",
    ],
    load: () => import("@/tools/platform-limits/tool"),
  }),
  defineTool({
    slug: "text-diff",
    title: "مقارنة نصّين",
    titleEn: "Text Diff",
    description: "الفروقُ سطراً سطراً، بإضافةٍ وحذفٍ ملوَّنَين.",
    category: "docs", subcategory: "analysis", icon: "diff", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فروق", "مقارنة", "diff", "نسختان", "تعديلات"],
    keywordsEn: ["diff", "compare text"],
    complexity: "medium",
    howItWorks: [
      "المقارنةُ بأطول تسلسلٍ مشترك — فالأسطرُ المنقولةُ تظهر حذفاً وإضافةً لا تعديلاً.",
      "زرُّ النسخ يعطيك الفروقَ بصيغة + و− المعتادة.",
    ],
    demo: { fields: { "td-a": "السعرُ ١٢٠ ريالاً شاملَ الضريبة", "td-b": "السعرُ ١٣٠ ريالاً شاملَ الضريبة" } },
    load: () => import("@/tools/text-diff/tool"),
  }),
  defineTool({
    slug: "markdown",
    title: "Markdown إلى HTML",
    titleEn: "Markdown to HTML",
    description: "معاينةٌ حيّةٌ ونسخُ الشيفرة — والنصُّ يُهرَّب فلا يمرّ وسم.",
    category: "docs", subcategory: "format", icon: "markdown", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["markdown", "html", "معاينة", "تنسيق", "نشر"],
    keywordsEn: ["markdown", "html", "preview"],
    complexity: "medium",
    howItWorks: [
      "يدعم العناوينَ والقوائمَ والاقتباسَ والروابطَ والشيفرةَ والخطَّ الفاصل.",
      "كلُّ ما تكتبه يُهرَّب أوّلاً ثمّ يُنسَّق، فلا يمرّ وسمٌ من نصّك إلى الصفحة.",
    ],
    demo: { fields: { "md-in": "# عنوان\n\nفقرةٌ فيها **عريض** و*مائل*.\n\n- بند\n- بند" } },
    load: () => import("@/tools/markdown/tool"),
  }),

  /* ————— حسابات وأعمال ————— */
  defineTool({
    slug: "number-to-words",
    title: "الأرقام إلى كلمات",
    titleEn: "Number to Words",
    description: "تفقيطُ المبالغ للفواتير والشيكات بالعربيّة والإنكليزيّة — بقواعد العدد الصحيحة.",
    category: "business", subcategory: "invoicing", icon: "numbers", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تفقيط", "كتابة المبلغ", "شيك", "فاتورة", "ليرة", "دولار", "ريال"],
    keywordsEn: ["number to words", "amount in words", "cheque"],
    complexity: "advanced",
    instructions: "اكتب الرقم واختر العملة — أو «بلا عملة» لقراءةٍ مجرّدة.",
    howItWorks: [
      "يطبّق قواعدَ العدد العربيّة: تمييزَ العدد، ومطابقةَ الجنس المعكوسة في ٣–١٠، والمثنّى.",
      "يراعي صيغَ الإضافة: «مئتا ألف» لا «مئتان ألف»، و«خمسون ألف ليرة» لا «ألفاً ليرة».",
      "يقبل الأرقامَ العربيّة-الهنديّة وفواصلَ الآلاف، حتّى ١٥ خانة.",
    ],
    useSteps: [
      "اكتب المبلغ بالأرقام — تُقبل الأرقامُ العربيّةُ الهنديّةُ (٠١٢) واللاتينيّة معاً.",
      "اختر العملةَ إن أردت صيغةَ الشيكات الكاملة، أو دعها فارغةً للعدد المجرّد.",
      "اقرأ الصيغةَ العربيّةَ والإنكليزيّةَ معاً وانسخ ما يلزمك.",
    ],
    examples: {
      caption: "مولَّدةٌ من دالّة التفقيط نفسِها، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["الرقم", "بالعربيّة", "بالإنكليزيّة"],
      rows: [
        ["7", "سبعة", "seven"],
        ["1250", "ألف ومئتان وخمسون", "one thousand two hundred fifty"],
        ["1000000", "مليون", "one million"],
        ["2500.75", "ألفان وخمسمئة فاصلة سبعة خمسة", "two thousand five hundred point seven five"],
      ],
    },
    deepDive: [
      {
        heading: "لماذا «خمسون ألفَ ليرة» لا «خمسون ألفاً ليرة»",
        body: "كلمةُ الألف والمليون حين تُضاف إلى معدودٍ بعدها تصير مضافاً، والمضافُ لا يُنوَّن ولا تلحقه نونُ المثنّى. فتقول «ألفُ ليرة» و«ألفا ليرة» و«خمسون ألفَ ليرة» — لا «ألفاً ليرة» ولا «ألفان ليرة». وهذا موضعٌ يخطئ فيه أكثرُ مولّدات التفقيط، والأداةُ هنا تفرّق بين العدد المجرّد والعدد المضاف إلى معدود.",
      },
      {
        heading: "التفقيطُ في الشيكات ولماذا يُطلب أصلاً",
        body: "الصيغةُ الكتابيّةُ ليست زينة: هي حمايةٌ من التزوير. رقمٌ مثل ١٠٠ يسهل أن يصير ١٠٠٠ بخطٍّ واحد، أمّا «مئة ليرةٍ لا غير» فلا تُمدّ. ولهذا تُختم العبارةُ بـ«لا غير» أو «فقط»، وتُكتب العملةُ صراحةً — وهو ما تفعله الأداةُ متى اخترت عملة.",
      },
    ],
    demo: { fields: { "ntw-input": "1250.75" } },
    load: () => import("@/tools/number-to-words/tool"),
  }),
  defineTool({
    slug: "vat",
    title: "ضريبة القيمة المضافة",
    titleEn: "VAT Calculator",
    description: "إضافةً واستخراجاً، بنسبِ البلدان جاهزةً أو نسبةٍ تختارها.",
    category: "business", subcategory: "tax", icon: "receipt", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ضريبة", "vat", "قيمة مضافة", "شامل الضريبة", "١٥٪", "فاتورة ضريبية"],
    keywordsEn: ["vat", "tax", "inclusive", "exclusive"],
    howItWorks: [
      "استخراجُ الضريبة من مبلغٍ شاملٍ ليس طرحَ النسبة، بل قسمةٌ على (١ + النسبة).",
      "خصمُ ١٥٪ من ١١٥٠ يعطي ٩٧٧٫٥ وهو خطأ؛ الصحيحُ ١٠٠٠.",
    ],
    useSteps: [
      "اختر «إضافة» إن كان المبلغ صافياً وتريد الضريبة فوقه، أو «استخراج» إن كان المبلغ شاملاً أصلاً.",
      "اكتب المبلغ.",
      "اختر النسبةَ من الأزرار الجاهزة، أو اكتبها إن كانت نسبةَ بلدك مختلفة.",
      "انسخ الصافيَ أو الضريبةَ أو الإجماليَّ — كلٌّ على حدة.",
    ],
    examples: {
      caption: "قيمٌ محسوبةٌ بالأداة نفسِها، ويتحقّق منها اختبارٌ آليٌّ في كلّ إصدار.",
      columns: ["الحالة", "المبلغ", "الصافي", "الضريبة", "الإجمالي"],
      rows: [
        ["إضافة 15٪", "1,000", "1,000.00", "150.00", "1,150.00"],
        ["استخراج 15٪", "1,000", "869.57", "130.43", "1,000.00"],
        ["إضافة 5٪", "1,000", "1,000.00", "50.00", "1,050.00"],
        ["استخراج 5٪", "1,000", "952.38", "47.62", "1,000.00"],
        ["إضافة 14٪", "2,500", "2,500.00", "350.00", "2,850.00"],
        ["استخراج 14٪", "2,500", "2,192.98", "307.02", "2,500.00"],
      ],
    },
    deepDive: [
      {
        heading: "لماذا لا تُطرح النسبةُ طرحاً عند الاستخراج",
        body: "أشيعُ غلطٍ في الفواتير أن يُطرح ١٥٪ من المبلغ الشامل لاستخراج الضريبة. والصوابُ أنّ الشاملَ يساوي الصافيَ مضروباً في ١٫١٥، فالصافي = الشامل ÷ ١٫١٥ والضريبةُ ما بقي. ولذلك ضريبةُ ألفٍ شاملةٍ ١٣٠٫٤٣ لا ١٥٠ — والفرقُ يتراكم عبر فواتير السنة حتّى يصير رقماً يُسأل عنه في التدقيق.",
      },
      {
        heading: "التقريبُ ومتى يُحدث فرقاً",
        body: "الحسابُ هنا يقرّب إلى منزلتين عشريّتين، وهو ما تفعله أنظمةُ الفوترة عادةً. لكنّ التقريبَ يجري عندنا على الإجمالي مرّةً واحدة، بينما بعضُ الأنظمة تقرّب كلَّ سطرٍ على حدة ثمّ تجمع — فيختلف المجموعُ بقرشٍ أو قرشين في فاتورةٍ متعدّدة البنود. إن طابقتَ فاتورتَك بنظامٍ محاسبيٍّ ووجدت فرقاً بهذا الحجم، فهذا سببُه لا خطأٌ في أحدهما.",
      },
    ],
    nextSteps: [
      { slug: "number-to-words", label: "اكتب المبلغ بالحروف", labelEn: "Write the amount in words", carry: { "v-a": "ntw-input" } },
      { slug: "invoice", label: "أنشئ فاتورةً بهذه النسبة", labelEn: "Create an invoice at this rate", carry: { "v-r": "in-t" } },
      { slug: "pricing", label: "راجِع هامشَ ربحك", labelEn: "Review your profit margin" },
    ],
    demo: { fields: { "v-a": "1000", "v-r": "15" } },
    load: () => import("@/tools/vat/tool"),
  }),
  defineTool({
    slug: "percentage",
    title: "النسبة المئويّة",
    titleEn: "Percentage Calculator",
    description: "ستُّ صيغٍ للسؤال في شاشةٍ واحدة — من الجزء إلى نسبة التغيّر.",
    category: "business", subcategory: "pricing", icon: "percent", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["نسبة", "مئوية", "زيادة", "نقصان", "تغير", "كم بالمئة"],
    keywordsEn: ["percentage", "percent change", "increase"],
    howItWorks: ["الخانتان تتبدّل تسميتُهما بحسب السؤال المختار، فلا تخلط الجزءَ بالكلّ."],
    demo: { fields: { "p-a": "45", "p-b": "180" } },
    load: () => import("@/tools/percentage/tool"),
  }),
  defineTool({
    slug: "pricing",
    title: "التسعير والهامش",
    titleEn: "Pricing & Margin",
    description: "من التكلفة إلى سعر البيع — ويفرّق بين الهامش والترميز.",
    category: "business", subcategory: "pricing", icon: "tag", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["هامش", "ربح", "تكلفة", "سعر بيع", "ترميز", "markup", "margin"],
    keywordsEn: ["margin", "markup", "profit", "cost price"],
    complexity: "medium",
    howItWorks: [
      "الهامشُ نسبةٌ من سعر البيع، والترميزُ نسبةٌ من التكلفة — والخلطُ بينهما أشهرُ غلطةِ تسعير.",
      "ترميزُ ٢٥٪ على تكلفة ١٠٠ يعطي هامشاً ٢٠٪ لا ٢٥٪.",
    ],
    nextSteps: [
      { slug: "vat", label: "أضِف الضريبة على سعر البيع", labelEn: "Add VAT to this price", carry: { "pr-p": "v-a" } },
      { slug: "discounts", label: "جرّب خصماً على هذا السعر", labelEn: "Try a discount on this price", carry: { "pr-p": "d-p" } },
      { slug: "invoice", label: "أنشئ فاتورةً بهذه الأرقام", labelEn: "Create an invoice from these numbers" },
    ],
    demo: { fields: { "pr-c": "60", "pr-p": "95" }, chips: { "المعطى": [2] } },
    load: () => import("@/tools/pricing/tool"),
  }),
  defineTool({
    slug: "discounts",
    title: "الخصومات المتتالية",
    titleEn: "Chained Discounts",
    description: "خصمٌ على خصمٍ — والنسبةُ الفعليّة التي لا تُجمع.",
    category: "business", subcategory: "pricing", icon: "scissors", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["خصم", "تنزيلات", "عروض", "سعر نهائي", "خصم على خصم"],
    keywordsEn: ["discount", "chained discount", "sale price"],
    howItWorks: ["٢٠٪ ثمّ ١٠٪ تساوي ٢٨٪ لا ٣٠٪، لأنّ الخصمَ الثاني يُحسب على ما بقي."],
    nextSteps: [
      { slug: "vat", label: "أضِف الضريبة على السعر النهائيّ", labelEn: "Add VAT to the final price" },
      { slug: "pricing", label: "تحقّق أنّ الخصم لم يأكل ربحك", labelEn: "Check the discount hasn't eaten your margin", carry: { "d-p": "pr-p" } },
    ],
    demo: { fields: { "d-p": "450", "d-c": "20, 10" } },
    load: () => import("@/tools/discounts/tool"),
  }),
  defineTool({
    slug: "timesheet",
    title: "ساعات العمل والأجر",
    titleEn: "Timesheet",
    description: "ورديّاتٌ تُجمع ساعاتُها — وتفهم العابرةَ منتصفَ الليل.",
    category: "business", subcategory: "payroll", icon: "clock", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["دوام", "ساعات", "ورديات", "أجر الساعة", "استراحة"],
    keywordsEn: ["timesheet", "work hours", "shift"],
    complexity: "medium",
    howItWorks: ["الورديّةُ العابرةُ منتصفَ الليل (٢٢:٠٠ ← ٠٦:٠٠) تُحسب ثماني ساعاتٍ لا سالباً."],
    nextSteps: [
      { slug: "invoice", label: "حوّل الساعات إلى فاتورة", labelEn: "Turn these hours into an invoice" },
      { slug: "end-of-service", label: "احسب مكافأةَ نهاية الخدمة", labelEn: "Calculate end-of-service benefit" },
    ],
    load: () => import("@/tools/timesheet/tool"),
  }),
  defineTool({
    slug: "split-bill",
    title: "تقسيم فاتورة",
    titleEn: "Split the Bill",
    description: "بين أشخاصٍ مع إكراميّة — حصّةُ كلٍّ بالضبط.",
    category: "business", subcategory: "finance", icon: "users", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تقسيم", "حساب", "مطعم", "إكرامية", "بقشيش", "حصة"],
    keywordsEn: ["split bill", "tip", "share"],
    nextSteps: [
      { slug: "percentage", label: "احسب نسبةَ الإكراميّة", labelEn: "Work out the tip percentage" },
      { slug: "vat", label: "افصل الضريبةَ عن الفاتورة", labelEn: "Separate the VAT from this bill", carry: { "sb-t": "v-a" } },
    ],
    demo: { fields: { "sb-t": "480", "sb-n": "4", "sb-p": "10" } },
    load: () => import("@/tools/split-bill/tool"),
  }),
  defineTool({
    slug: "iban",
    title: "مدقّق IBAN",
    titleEn: "IBAN Validator",
    description: "تحقّقٌ محلّيٌّ بمعيار mod-97 قبل أن تُرسل حوالةً إلى رقمٍ خاطئ.",
    category: "business", subcategory: "banking", icon: "bank", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ايبان", "حساب بنكي", "حوالة", "تحقق", "رقم حساب دولي"],
    keywordsEn: ["iban", "bank account", "validate", "mod-97"],
    complexity: "medium",
    howItWorks: [
      "المعيارُ mod-97: تُنقل الأربعةُ الأولى إلى الآخر، وتُبدَّل الحروفُ أرقاماً، فالباقي يجب أن يكون ١.",
      "التحقّقُ يثبت سلامةَ الكتابة لا وجودَ الحساب — فالبنكُ وحده يعرف ذلك.",
      "لا يغادر الرقمُ متصفّحَك.",
    ],
    demo: { fields: { "ib-in": "SA0380000000608010167519" } },
    load: () => import("@/tools/iban/tool"),
  }),
  defineTool({
    slug: "loan",
    title: "جدول سداد قرض",
    titleEn: "Loan Amortization",
    description: "القسطُ الشهريّ وجدولُ الأصل والفائدة شهراً شهراً.",
    category: "business", subcategory: "finance", icon: "loan", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["قرض", "تمويل", "قسط", "فائدة", "جدول سداد", "تمويل عقاري"],
    keywordsEn: ["loan", "amortization", "installment", "interest"],
    complexity: "medium",
    howItWorks: [
      "أقساطٌ ثابتةٌ بطريقة التناقص — الفائدةُ على الرصيد المتبقّي لا على أصل المبلغ.",
      "القسطُ الأخير يبتلع فروقَ التقريب فينتهي الرصيدُ صفراً تماماً.",
    ],
    nextSteps: [
      { slug: "percentage", label: "احسب نسبةَ القسط من دخلك", labelEn: "What share of your income is this instalment?" },
      { slug: "number-to-words", label: "اكتب مبلغَ القرض بالحروف", labelEn: "Write the loan amount in words", carry: { "l-a": "ntw-input" } },
    ],
    demo: { fields: { "l-a": "120000", "l-r": "6.5", "l-m": "60" } },
    load: () => import("@/tools/loan/tool"),
  }),
  defineTool({
    slug: "zakat",
    title: "حاسبة الزكاة",
    titleEn: "Zakat Calculator",
    description: "نقدٌ وذهبٌ وفضّةٌ وعروضُ تجارة، بنصابِ الذهب أو الفضّة.",
    category: "business", subcategory: "finance", icon: "crescent", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["زكاة", "نصاب", "ذهب", "فضة", "عروض تجارة", "ربع العشر"],
    keywordsEn: ["zakat", "nisab", "gold", "silver"],
    complexity: "medium",
    howItWorks: [
      "المعدّل ربعُ العشر (٢٫٥٪) على ما بلغ النصابَ وحال عليه الحول.",
      "النصاب ٨٥ غراماً ذهباً أو ٥٩٥ غراماً فضّة — والأخذُ بالفضّة أحوطُ للفقراء.",
      "أسعارُ الغرام تُدخلها بنفسك؛ الحقيبةُ لا تتّصل بمصدرٍ خارجيّ.",
    ],
    load: () => import("@/tools/zakat/tool"),
  }),
  defineTool({
    slug: "end-of-service",
    title: "مكافأة نهاية الخدمة",
    titleEn: "End of Service Benefit",
    description: "تقديرٌ إرشاديٌّ بأنظمة السعوديّة والإمارات أو صيغةٍ تحدّدها.",
    category: "business", subcategory: "payroll", icon: "award", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["نهاية الخدمة", "مكافأة", "استقالة", "تعويض", "عمل"],
    keywordsEn: ["end of service", "gratuity", "severance"],
    complexity: "medium",
    howItWorks: [
      "تقديرٌ إرشاديٌّ لا فتوى قانونيّة — الأنظمةُ تتغيّر.",
      "المستحقُّ يختلف بسبب انتهاء الخدمة (استقالةٌ أم إنهاء) وبما يدخل في «الأجر».",
    ],
    demo: { fields: { "e-w": "8000" } },
    load: () => import("@/tools/end-of-service/tool"),
  }),
  defineTool({
    slug: "invoice",
    title: "فاتورة للطباعة",
    titleEn: "Printable Invoice",
    description: "نموذجٌ عربيٌّ يُملأ ويُطبع أو يُحفظ PDF من المتصفّح.",
    category: "business", subcategory: "invoicing", icon: "receipt", version: "1.0.0", publishedAt: "2026-08-30",
    capabilities: { print: true, exportPdf: true, exportCsv: true, saveDraft: true },
    keywords: ["فاتورة", "طباعة", "pdf", "عميل", "بنود", "ضريبة"],
    keywordsEn: ["invoice", "print", "pdf", "billing"],
    complexity: "advanced",
    howItWorks: [
      "المعاينةُ هي نفسُها ما يُطبع — لا مفاجأةَ في الورقة.",
      "الطباعةُ تُخفي حقولَ الإدخال وقشرةَ الموقع، و«حفظ PDF» في نافذة الطباعة يعطيك ملفّاً بلا مكتبةٍ إضافيّة.",
    ],
    nextSteps: [
      { slug: "number-to-words", label: "اكتب الإجماليَّ بالحروف", labelEn: "Write the total in words" },
      { slug: "iban", label: "تحقّق من رقم الآيبان قبل الإرسال", labelEn: "Validate the IBAN before sending" },
    ],
    load: () => import("@/tools/invoice/tool"),
  }),

  /* ————— تحويلات وقياسات ————— */
  defineTool({
    slug: "hijri-gregorian",
    title: "التقويم الهجريّ والميلاديّ",
    titleEn: "Hijri ↔ Gregorian",
    description: "تحويلٌ في الاتّجاهين مع اسم اليوم — أمّ القرى أو الحسابيّ المدنيّ.",
    category: "convert", subcategory: "datetime", icon: "calendar", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["هجري", "ميلادي", "تقويم", "أم القرى", "تاريخ", "رمضان", "تحويل تاريخ"],
    keywordsEn: ["hijri", "gregorian", "islamic calendar", "umm al-qura"],
    complexity: "advanced",
    howItWorks: [
      "يبني على تقويم المتصفّح المدمج (ICU) — لا مكتبةَ خارجيّةً ولا جداولَ منسوخة.",
      "أمّ القرى والحسابيّ المدنيّ يختلفان بيومٍ في نحو نصف الأشهر — والخيارُ لك.",
      "التقويمُ حسابيٌّ لا رَصْديّ، وقد يفارق رؤيةَ الهلال المحلّيّة يوماً.",
    ],
    nextSteps: [
      { slug: "date-diff", label: "احسب الفرقَ بين تاريخين", labelEn: "Work out the gap between two dates" },
      { slug: "prayer-times", label: "مواقيتُ الصلاة في هذا اليوم", labelEn: "Prayer times for this day" },
    ],
    load: () => import("@/tools/hijri-gregorian/tool"),
  }),

  defineTool({
    slug: "units",
    title: "محوّل الوحدات",
    titleEn: "Unit Converter",
    description: "طولٌ ووزنٌ وحجمٌ ومساحةٌ وسرعةٌ وزمنٌ وحرارة — بجدولٍ يعرض كلَّ الوحدات معاً.",
    descriptionEn: "Length, mass, volume, area, speed, time and temperature — with a table that shows every unit at once.",
    category: "convert", subcategory: "units", icon: "ruler", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["وحدات", "تحويل", "متر", "قدم", "كيلو", "رطل", "لتر", "مئوي", "فهرنهايت", "ميل"],
    keywordsEn: ["unit converter", "metric", "imperial", "celsius", "fahrenheit"],
    complexity: "medium",
    instructions: "اختر النوعَ ثمّ الوحدتين — والجدولُ أسفلَه يعطيك القيمةَ بكلّ الوحدات دفعةً واحدة.",
    howItWorks: [
      "كلُّ وحدةٍ لها معاملٌ إلى وحدةٍ أساسٍ، والتحويلُ ضربٌ وقسمة — فلا يتراكم خطأُ التقريب.",
      "الحرارةُ ليست نسبيّةً كالطول (صفرُها ليس عدماً)، فلها مسارُ تحويلٍ خاصٌّ ونوعٌ مستقلّ.",
    ],
    useSteps: [
      "اختر النوعَ أوّلاً: طولٌ أو كتلةٌ أو حجمٌ أو حرارة…",
      "اكتب القيمةَ واختر الوحدتين، أو اضغط ⇄ لعكس الاتّجاه.",
      "اقرأ الجدولَ أسفلَه — يعطيك القيمةَ بكلّ وحدات النوع دفعةً واحدة.",
    ],
    examples: {
      caption: "قيمٌ محسوبةٌ بالأداة نفسِها، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["التحويل", "النتيجة"],
      rows: [
        ["1 متر → قدم", "3.28084 ft"],
        ["1 إنش → سنتيمتر", "2.54 cm"],
        ["1 ميل → كيلومتر", "1.609344 km"],
        ["100 كم → ميل", "62.137119 mi"],
        ["1 كيلوغرام → رطل", "2.204623 lb"],
        ["70 كغ → رطل", "154.323584 lb"],
        ["0 °م → فهرنهايت", "32 °F"],
        ["37 °م → فهرنهايت", "98.6 °F"],
        ["100 °م → فهرنهايت", "212 °F"],
      ],
    },
    nextSteps: [
      { slug: "number-to-words", label: "اكتب الناتجَ بالحروف", labelEn: "Write the result in words" },
      { slug: "coordinates", label: "حوّل إحداثيّاتٍ جغرافيّة", labelEn: "Convert geographic coordinates" },
    ],
    demo: { fields: { "u-v": "70" } },
    langs: ["ar", "en"],
    instructionsEn: "Pick the type, then the two units — the table below gives you the value in every unit at once.",
    useStepsEn: [
      "Choose the type first: length, mass, volume, temperature…",
      "Enter a value and pick the two units, or press ⇄ to reverse.",
      "Read the table below — it converts to every unit in that family at once.",
    ],
    howItWorksEn: [
      "Every unit carries a factor to one base unit, so conversion is one multiply and one divide — rounding error never accumulates.",
      "Temperature is not proportional (its zero is not nothing), so it has its own conversion path and its own type.",
    ],
    load: () => import("@/tools/units/tool"),
  }),
  defineTool({
    slug: "date-diff",
    title: "الفرق بين تاريخين",
    titleEn: "Date Difference",
    description: "بالسنين والأشهر والأيّام معاً، ومجموعِ الأيّام والأسابيع.",
    category: "convert", subcategory: "datetime", icon: "calendarDiff", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["فرق تاريخين", "مدة", "كم يوم", "حساب المدة", "عقد", "مدة العقد"],
    keywordsEn: ["date difference", "days between", "duration"],
    howItWorks: [
      "الأشهرُ تُعدّ بالتقويم لا بمتوسّطٍ ثابت: نأخذ أكبرَ عددِ أشهرٍ يبقى ضمن المدّة ثمّ نعدّ الأيّامَ الباقية.",
      "«٣١ كانون الثاني + شهر» تساوي آخرَ شباط بالقصّ — فالمدّةُ بينهما شهرٌ تامّ لا ناقص.",
    ],
    demo: { fields: { "dd-a": "2026-01-01", "dd-b": "2026-08-30" } },
    load: () => import("@/tools/date-diff/tool"),
  }),
  defineTool({
    slug: "age",
    title: "حاسبة العمر",
    titleEn: "Age Calculator",
    description: "عمرُك بالسنين والأشهر والأيّام، ويومُ ميلادك، وموعدُ ميلادك القادم.",
    category: "convert", subcategory: "datetime", icon: "cake", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["العمر", "كم عمري", "تاريخ الميلاد", "عيد ميلاد", "سنّ"],
    keywordsEn: ["age calculator", "birthday", "how old"],
    howItWorks: [
      "الحسابُ تقويميٌّ لا بمتوسّط، فالسنواتُ الكبيسةُ محسوبةٌ على حقيقتها.",
      "يومُ الميلاد يُشتقّ من التاريخ نفسه — لا حاجةَ إلى جدول.",
    ],
    load: () => import("@/tools/age/tool"),
  }),
  defineTool({
    slug: "business-days",
    title: "أيّام العمل",
    titleEn: "Business Days",
    description: "أيّامُ العمل بين تاريخين مع اختيار عطلة الأسبوع وطرحِ العطل الرسميّة.",
    category: "convert", subcategory: "datetime", icon: "briefcase", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["أيام عمل", "دوام", "عطلة", "مدة تسليم", "أيام عمل فعلية"],
    keywordsEn: ["business days", "working days", "weekend"],
    complexity: "medium",
    howItWorks: [
      "عطلةُ الأسبوع تختلف بين البلدان — الجمعةُ والسبت في أكثر البلاد العربيّة، والسبتُ والأحد في غيرها.",
      "العطلةُ الرسميّةُ التي تصادف نهايةَ الأسبوع لا تُطرح مرّتين.",
      "الطرفان محسوبان ضمن المدّة.",
    ],
    load: () => import("@/tools/business-days/tool"),
  }),
  defineTool({
    slug: "timezones",
    title: "المناطق الزمنيّة",
    titleEn: "Time Zones",
    description: "كم الساعةُ هناك — مع جدولٍ يعرض اللحظةَ نفسَها في مدنٍ كثيرة.",
    category: "convert", subcategory: "datetime", icon: "globe", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["توقيت", "فرق التوقيت", "مناطق زمنية", "اجتماع", "كم الساعة", "توقيت صيفي"],
    keywordsEn: ["timezone", "time difference", "meeting time"],
    complexity: "medium",
    howItWorks: [
      "الإزاحاتُ يحسبها متصفّحك بجدول المناطق المدمج، فيراعي التوقيتَ الصيفيّ في تاريخ سؤالك لا في تاريخ اليوم.",
      "لذلك يتغيّر الفرقُ بين مدينتين بحسب الشهر — وهذا صحيحٌ لا خطأ.",
    ],
    load: () => import("@/tools/timezones/tool"),
  }),
  defineTool({
    slug: "file-size",
    title: "حجوم الملفّات",
    titleEn: "File Size Converter",
    description: "بايتٌ وكيلوٌ وميغا وغيغا — وبالأساسين ١٠٠٠ و١٠٢٤ معاً.",
    category: "convert", subcategory: "units", icon: "drive", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["حجم ملف", "ميغابايت", "غيغابايت", "بايت", "سعة", "قرص"],
    keywordsEn: ["file size", "megabyte", "gigabyte", "bytes"],
    howItWorks: [
      "الأساس ١٠٢٤ ما يعرضه نظامُ التشغيل، والأساس ١٠٠٠ ما يكتبه صنّاعُ الأقراص.",
      "لذلك يبدو قرصُ «١ تيرابايت» ٩٣١ غيبيبايت بعد التركيب — والفرقُ ليس عطلاً.",
    ],
    load: () => import("@/tools/file-size/tool"),
  }),
  defineTool({
    slug: "number-base",
    title: "أنظمة العدّ",
    titleEn: "Number Base Converter",
    description: "ثنائيٌّ وثمانيٌّ وعشريٌّ وستّ عشريّ — بأعدادٍ كبيرةٍ بلا فقدِ دقّة.",
    category: "convert", subcategory: "numbers", icon: "binary", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ثنائي", "hex", "ست عشري", "binary", "أساس", "تحويل أنظمة"],
    keywordsEn: ["binary", "hexadecimal", "base converter"],
    howItWorks: [
      "الحسابُ بأعدادٍ صحيحةٍ غيرِ محدودة (BigInt)، فالأعدادُ الكبيرةُ تُحوَّل بلا تقريب.",
      "المحرفُ غيرُ المسموح في الأساس يُكشف باسمه بدل نتيجةٍ خاطئةٍ صامتة.",
    ],
    load: () => import("@/tools/number-base/tool"),
  }),
  defineTool({
    slug: "coordinates",
    title: "تحويل الإحداثيّات",
    titleEn: "Coordinate Converter",
    description: "درجاتٌ عشريّة ↔ درجة ودقيقة وثانية، في الاتّجاهين.",
    category: "convert", subcategory: "units", icon: "pin", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["إحداثيات", "خط طول", "خط عرض", "gps", "خرائط", "درجة دقيقة ثانية"],
    keywordsEn: ["coordinates", "dms", "latitude", "longitude", "gps"],
    complexity: "medium",
    howItWorks: [
      "الصيغةُ العشريّةُ ما تقبله الخرائطُ عادةً، والدرجاتُ والدقائقُ والثواني ما تجده في الوثائق المساحيّة.",
      "السالبُ جنوباً وغرباً — والأداةُ ترفض ما يتجاوز حدودَ الكرة.",
    ],
    load: () => import("@/tools/coordinates/tool"),
  }),
  defineTool({
    slug: "clothing-sizes",
    title: "مقاسات الملابس والأحذية",
    titleEn: "Clothing & Shoe Sizes",
    description: "جداولُ أوروبا وبريطانيا وأمريكا للملابس والأحذية، رجاليّةً ونسائيّة.",
    category: "convert", subcategory: "units", icon: "shirt", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["مقاسات", "أحذية", "ملابس", "تسوق", "شراء اونلاين", "مقاس أوروبي"],
    keywordsEn: ["size chart", "shoe size", "clothing size"],
    howItWorks: [
      "الجداولُ إرشاديّة: المقاساتُ تختلف بين العلامات التجاريّة اختلافاً حقيقيّاً.",
      "للأحذية قِس طولَ قدمك بالسنتيمتر — فهو أدقُّ من أيّ رقمِ مقاس.",
    ],
    load: () => import("@/tools/clothing-sizes/tool"),
  }),
  defineTool({
    slug: "prayer-times",
    title: "مواقيت الصلاة",
    titleEn: "Prayer Times",
    description: "حسابٌ فلكيٌّ في متصفّحك بستّ طرقٍ ومذهبَي العصر — بلا إنترنتٍ ولا تتبّعِ موقع.",
    category: "convert", subcategory: "datetime", icon: "mosque", version: "1.0.0", publishedAt: "2026-08-30",
    status: "beta",
    complexity: "advanced",
    keywords: ["مواقيت الصلاة", "أذان", "الفجر", "المغرب", "العشاء", "القبلة", "أم القرى", "شروق"],
    keywordsEn: ["prayer times", "salah", "adhan", "fajr", "maghrib"],
    tags: ["حسابٌ فلكيّ", "تجريبيّة"],
    instructions: "اختر مدينتك أو أدخل إحداثيّاتٍ — لا يُطلب موقعُك ولا يُرسَل شيء.",
    howItWorks: [
      "الحسابُ فلكيٌّ قياسيّ: موضعُ الشمس (الميلُ ومعادلةُ الزمن) ثمّ زاويةُ الساعة لكلّ ارتفاعٍ مطلوب.",
      "الطرقُ تختلف في زاويتَي الفجر والعشاء، وأمّ القرى تجعل العشاءَ بعد المغرب بتسعين دقيقة.",
      "العصرُ عند الجمهور حين يصير ظلُّ الشيء مثلَه، وعند الحنفيّة مثلَيه.",
      "تحقّقٌ داخليّ: الظهرُ يطابق منتصفَ ما بين الشروق والغروب، وطولُ النهار يطابق القيمَ المعروفة.",
      "الأشهرُ الرسميّةُ قد تفارقه دقائقَ لاختلاف الطريقة أو الاحتياط — اعتمد إعلانَ بلدك.",
    ],
    faq: [
      { q: "لماذا تختلف عن تقويم بلدي بدقيقة أو دقيقتين؟",
        a: "لأنّ الهيئاتِ تختلف في الزوايا وفي التقريب والاحتياط. جرّب تبديلَ طريقة الحساب لتقترب من تقويمك، والفرقُ الباقي مقصودٌ عندهم غالباً." },
      { q: "هل يُرسَل موقعي؟",
        a: "لا. الحسابُ كلُّه في متصفّحك، والمدنُ جدولٌ مخزَّنٌ في الأداة. وإن أدخلتَ إحداثيّاتٍ فهي تبقى عندك." },
      { q: "لماذا الأداةُ موسومةٌ «تجريبيّة»؟",
        a: "لأنّ الحسابَ الفلكيَّ مُتحقَّقٌ منه داخليّاً لكنّه لم يُقارَن بعدُ بتقاويم كلّ البلدان. استعمله للتقدير والتخطيط، واعتمد إعلانَ بلدك للصلاة." },
    ],
    load: () => import("@/tools/prayer-times/tool"),
  }),

  /* ————— مطوّرون ————— */
  defineTool({
    slug: "base64",
    title: "ترميز Base64",
    titleEn: "Base64 Encoder & Decoder",
    description: "نصٌّ ↔ Base64 بترميز UTF-8 سليمٍ للعربيّة، وبالصيغة الآمنة للروابط.",
    descriptionEn: "Text ↔ Base64 with proper UTF-8, plus the URL-safe variant used by JWT.",
    category: "dev", subcategory: "encoding", icon: "binary", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["base64", "ترميز", "فكّ ترميز", "تشفير", "بيس 64", "روابط", "base64url"],
    keywordsEn: ["base64", "encode", "decode", "base64url"],
    instructions: "اختر الاتّجاهَ وألصق النصّ — يُحسب فوراً في متصفّحك.",
    howItWorks: [
      "الترميزُ يمرّ ببايتات UTF-8 أوّلاً، فالعربيّةُ تعود كما دخلت — بخلاف btoa المباشر الذي ينهار عند أوّل حرفٍ عربيّ.",
      "الصيغةُ الآمنةُ للروابط تستبدل - و_ بـ+ و/ وتحذف الحشو =، وهي صيغةُ أجزاء JWT.",
      "‏Base64 تمثيلٌ لا تشفير: يفكُّه أيُّ أحدٍ بلا مفتاح.",
    ],
    faq: [
      { q: "لماذا فشل فكُّ نصٍّ يبدو صالحاً؟", a: "إمّا أنّ طولَه لا يقبل القسمةَ على أربعةٍ بعد الحشو، وإمّا أنّ البايتات الناتجةَ ليست نصَّ UTF-8 — كأن يكون المصدرُ ملفّاً ثنائيّاً كصورة." },
      { q: "هل يصلح لإخفاء كلمةِ مرور؟", a: "لا. ‏Base64 ليس تشفيراً، وفكُّه لا يحتاج مفتاحاً ولا جهداً." },
    ],
    useSteps: [
      "اختر الاتّجاه: نصٌّ ← Base64 أو العكس.",
      "ألصق النصّ — تظهر النتيجةُ فوراً بلا زرّ تنفيذ.",
      "إن كنت ترمّز جزءاً من رابطٍ أو حمولةَ JWT فاختر «آمنةٌ للروابط».",
      "اضغط «اعكس الاتّجاه» لتتحقّق أنّ النصَّ يعود كما كان.",
    ],
    examples: {
      caption: "مولَّدةٌ من دالّة الترميز نفسِها، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["النصّ", "Base64"],
      rows: [
        ["Do Kits", "RG8gS2l0cw=="],
        ["مرحبا", "2YXYsdit2KjYpw=="],
        ["حقيبة أدوات", "2K3ZgtmK2KjYqSDYo9iv2YjYp9iq"],
      ],
    },
    deepDive: [
      {
        heading: "لماذا تنهار أكثرُ الأدوات عند أوّل حرفٍ عربيّ",
        body: "دالّةُ btoa في المتصفّح تقبل بايتاتٍ لا محارف، فكلُّ محرفٍ فوق 255 يرمي خطأً. والحلُّ أن يُرمَّز النصُّ إلى UTF-8 أوّلاً ثمّ يُحوَّل — وهو ما تفعله هذه الأداة. ولهذا ترى «مرحبا» تصير ثمانيةَ بايتاتٍ لا خمسة: كلُّ حرفٍ عربيٍّ بايتان في UTF-8. وحين ترى ناتجَ ترميزٍ عربيٍّ يبدأ بـ2K أو 2Y فذلك دليلُ سلامته.",
      },
      {
        heading: "الحشوُ = والصيغةُ الآمنةُ للروابط",
        body: "‏Base64 يعمل على ثلاثة بايتاتٍ يخرجها أربعةَ محارف، فإن لم يقبل الطولُ القسمةَ على ثلاثةٍ حُشي الناتجُ بعلامةِ = أو علامتين. وهذه العلامةُ لها معنًى خاصٌّ في الروابط، كما أنّ + و/ تُفسَّران تفسيراً آخر — لذلك وُضعت صيغةُ Base64URL التي تبدّلهما بـ- و_ وتحذف الحشو. وهي صيغةُ أجزاء JWT، ولهذا لا ترى فيها علامةَ = قطّ.",
      },
    ],
    demo: { fields: { "b64-in": "حقيبةُ أدواتٍ عربيّة" } },
    langs: ["ar", "en"],
    instructionsEn: "Pick a direction and paste your text — it converts as you type, in your browser.",
    useStepsEn: [
      "Choose the direction: text → Base64, or the reverse.",
      "Paste the text — the result appears immediately, with no run button.",
      "If you are encoding part of a URL or a JWT segment, switch to the URL-safe variant.",
      "Press Reverse direction to confirm the text round-trips unchanged.",
    ],
    howItWorksEn: [
      "Encoding goes through UTF-8 bytes first, so non-Latin text survives — unlike plain btoa, which throws on the first non-Latin character.",
      "The URL-safe variant swaps - and _ for + and / and drops the = padding; this is the form JWT uses.",
      "Base64 is a representation, not encryption: anyone can reverse it without a key.",
    ],
    load: () => import("@/tools/base64/tool"),
  }),
  defineTool({
    slug: "url-tools",
    title: "ترميز الروابط وتشريحها",
    titleEn: "URL Encoder & Parser",
    description: "ترميزُ أجزاء الرابط وفكُّها، وتشريحُ رابطٍ إلى أجزائه ومعاملاته مفكوكةً.",
    descriptionEn: "Encode and decode URL parts, and break a URL into its pieces with the parameters decoded.",
    category: "dev", subcategory: "encoding", icon: "link", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["رابط", "url", "ترميز", "معاملات", "استعلام", "query", "percent encoding"],
    keywordsEn: ["url encode", "url decode", "query string", "parse url"],
    complexity: "medium",
    instructions: "رمّز جزءاً، أو فُكَّ ترميزاً، أو ألصق رابطاً كاملاً لتشريحه.",
    howItWorks: [
      "‏encodeURIComponent يرمّز كلَّ شيءٍ بما فيه : / ? & — وهو الصحيحُ لقيمةِ معامل.",
      "‏encodeURI يبقي فواصلَ الرابط سليمةً — وهو الصحيحُ للرابط الكامل.",
      "التشريحُ يعرض القيمَ مفكوكةَ الترميز، أي كما يقرؤها الخادمُ لا كما تظهر في شريط العنوان.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Encode a part, decode one, or paste a whole URL to take it apart.",
    useStepsEn: [
      "Choose encode, decode, or parse.",
      "For encoding, pick whether it is one parameter value or a whole URL.",
      "Paste the text — the result updates as you type.",
    ],
    howItWorksEn: [
      "encodeURIComponent encodes everything including : / ? & — correct for one parameter value.",
      "encodeURI leaves the URL separators intact — correct for a whole URL.",
      "The parse view shows values decoded, i.e. as the server reads them, not as the address bar displays them.",
    ],
    load: () => import("@/tools/url-tools/tool"),
  }),
  defineTool({
    slug: "unicode-inspect",
    title: "مفتّش المحارف",
    titleEn: "Unicode Character Inspector",
    description: "يكشف المحارفَ الخفيّةَ وعلاماتِ الاتّجاه التي تكسر البحثَ والمطابقة، ويسمّي كلَّ محرفٍ باسمه.",
    descriptionEn: "Reveals the invisible characters and directional marks that break search and matching.",
    category: "dev", subcategory: "encoding", icon: "glyph", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["يونيكود", "محارف خفيّة", "اتّجاه", "تطويل", "بحث لا يجد", "نقطة ترميز", "utf-8", "توحيد"],
    keywordsEn: ["unicode", "code point", "invisible characters", "normalization", "utf-8"],
    complexity: "medium",
    instructions: "ألصق نصّاً يسلك سلوكاً غريباً — بحثٌ لا يجده، أو اسمٌ لا يطابق نفسَه.",
    howItWorks: [
      "الجدولُ يعرض لكلّ محرفٍ نقطةَ ترميزه وبايتات UTF-8 واسمَه — والخفيُّ منها مُعلَّمٌ بلونٍ ظاهر.",
      "طولُ النصّ بالمحارف يخالف عددَ نقاط الترميز متى وُجد رمزٌ تعبيريّ، ويخالف عددَ البايتات دائماً في العربيّة.",
      "صيغةُ NFC توحّد ما يُرسم متماثلاً ويُخزَّن مختلفاً — وهي ما ينبغي حفظُه في القاعدة.",
    ],
    faq: [
      { q: "لماذا لا يجد البحثُ اسماً أراه بعيني؟", a: "غالباً بسبب تطويلٍ (ـ) أو مسافةٍ غير فاصلة أو علامةِ اتّجاهٍ ألصقها النسخُ من صفحةِ ويب. ألصق النصَّ هنا واضغط «احذف الخفيّة»." },
    ],
    demo: { fields: { "uc-in": "عبادة‏ مـــحمد" } },
    langs: ["ar", "en"],
    instructionsEn: "Paste anything behaving strangely — a search that finds nothing, or a name that will not match itself.",
    useStepsEn: [
      "Paste the text.",
      "Read the tiles: length, code points, UTF-8 bytes and how many characters are invisible.",
      "Use \"Remove the invisible ones\" to get a clean copy.",
    ],
    howItWorksEn: [
      "The table gives each character's code point, its UTF-8 bytes and what it is — invisible ones are highlighted.",
      "Character length differs from code-point count whenever an emoji is present, and always differs from byte count in non-Latin text.",
      "NFC unifies what renders identically but is stored differently — it is what belongs in your database.",
    ],
    load: () => import("@/tools/unicode-inspect/tool"),
  }),
  defineTool({
    slug: "json-format",
    title: "منسّق JSON ومدقّقه",
    titleEn: "JSON Formatter & Validator",
    description: "تنسيقٌ وضغطٌ وترتيبُ مفاتيح، وموضعُ الخطأ سطراً وعموداً — كلُّه في متصفّحك.",
    descriptionEn: "Format, minify, sort keys and locate the error by line and column — all in your browser.",
    category: "dev", subcategory: "data", icon: "braces", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["json", "تنسيق", "تدقيق", "ضغط", "مفاتيح", "خطأ", "صيغة"],
    keywordsEn: ["json formatter", "json validator", "prettify", "minify"],
    complexity: "medium",
    instructions: "ألصق JSON — يُدقَّق ويُنسَّق فوراً، ويُشار إلى موضع الخطأ إن وُجد.",
    howItWorks: [
      "موضعُ الخطأ يُحسب من فهرس المحرف لا من نصّ رسالة المتصفّح — فصياغةُ الرسائل تختلف بين المحرّكات وتتبدّل بين الإصدارات.",
      "ترتيبُ المفاتيح عميقٌ يشمل الكائناتِ المتداخلة، وهو ما يجعل مقارنةَ ملفّين ممكنة.",
      "لا يُرسَل ملفُّك إلى خادم، فلصقُ استجابةٍ فيها بياناتُ عملاءَ آمنٌ هنا.",
    ],
    nextSteps: [
      { slug: "csv-json", label: "حوّله إلى CSV", labelEn: "Convert it to CSV" },
      { slug: "base64", label: "رمّزه بـBase64", labelEn: "Encode it as Base64" },
    ],
    demo: { fields: { "jf-in": "{\"name\":\"Do Kits\",\"tools\":53,\"local\":true}" } },
    langs: ["ar", "en"],
    instructionsEn: "Paste JSON — it is validated and formatted instantly, with the error position if there is one.",
    useStepsEn: [
      "Paste the JSON.",
      "Choose the indentation, or minify.",
      "Sort the keys if you are about to diff two files.",
      "Copy the result.",
    ],
    howItWorksEn: [
      "The error position is computed from the character index rather than parsed out of the engine's message, because engines word those differently and change them between versions.",
      "Key sorting is deep, covering nested objects — which is what makes two files comparable.",
      "Nothing is sent to a server, so pasting a response containing customer data is safe here.",
    ],
    load: () => import("@/tools/json-format/tool"),
  }),
  defineTool({
    slug: "csv-json",
    title: "تحويل CSV و JSON",
    titleEn: "CSV ⇄ JSON Converter",
    description: "في الاتّجاهين، مع احترام الاقتباس والفواصل داخل القيم واختلاف الأعمدة بين الصفوف.",
    descriptionEn: "Both directions, respecting quoting, embedded commas and objects with differing keys.",
    category: "dev", subcategory: "data", icon: "table", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["csv", "json", "تحويل", "جدول", "إكسل", "بيانات", "فاصل"],
    keywordsEn: ["csv to json", "json to csv", "convert", "spreadsheet"],
    complexity: "medium",
    capabilities: { exportCsv: true },
    instructions: "اختر الاتّجاهَ والفاصل، ثمّ ألصق البيانات.",
    howItWorks: [
      "المحلّلُ يحترم الاقتباس: فاصلةٌ أو سطرٌ جديدٌ داخل «…» جزءٌ من القيمة لا فاصلٌ بينها.",
      "عند التحويل إلى CSV تُجمَع أعمدةُ كلِّ الكائنات، فالكائنُ الناقصُ مفتاحاً يُترك حقلُه فارغاً بدل أن تختلَّ الأعمدة.",
      "الفواصلُ المدعومة أربعة، لأنّ إكسل العربيَّ كثيراً ما يحفظ بالفاصلة المنقوطة.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Choose the direction and the delimiter, then paste your data.",
    useStepsEn: [
      "Choose the direction and the delimiter.",
      "Say whether the first CSV row is a header.",
      "Paste the data and copy the result.",
    ],
    howItWorksEn: [
      "The parser respects quoting: a comma or newline inside quotes is part of the value, and a doubled quote means one literal quote.",
      "Converting to CSV unions the keys of every object, so a missing key leaves an empty field rather than shifting the columns.",
      "Four delimiters are supported because Excel in many locales saves with semicolons.",
    ],
    load: () => import("@/tools/csv-json/tool"),
  }),
  defineTool({
    slug: "jwt-decode",
    title: "قارئ JWT",
    titleEn: "JWT Decoder",
    description: "يفكّ ترويسةَ الرمز وحمولتَه ويسمّي مطالبَه ويحوّل أزمنتَه إلى تواريخَ مقروءة.",
    descriptionEn: "Decodes a token's header and payload, names its claims and turns timestamps into readable dates.",
    category: "dev", subcategory: "security", icon: "key", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["jwt", "رمز", "توكن", "مطالب", "صلاحيّة", "انتهاء", "bearer", "مصادقة"],
    keywordsEn: ["jwt decoder", "token", "claims", "bearer"],
    complexity: "medium",
    instructions: "ألصق الرمزَ — يُفكُّ في متصفّحك ولا يُرسَل إلى خادم.",
    howItWorks: [
      "الأداةُ تفكّ ولا تتحقّق: التحقّقُ من التوقيع يحتاج المفتاحَ السرّيّ، وإدخالُ المفتاح في صفحةِ ويب خطأٌ في ذاته.",
      "حمولةُ JWT ليست مشفّرة — هي Base64URL يقرؤها أيُّ حاملٍ للرمز.",
      "تُعلَن الخوارزميّةُ صراحةً، فـalg=none يعني رمزاً بلا توقيعٍ إطلاقاً.",
    ],
    faq: [
      { q: "هل يُرسَل رمزي إلى مكانٍ ما؟", a: "لا، الفكُّ يجري في متصفّحك. ومع ذلك العادةُ الأسلمُ أن تُجرّب برمزِ اختبارٍ لا برمزِ إنتاج." },
      { q: "لماذا لا تتحقّق الأداةُ من التوقيع؟", a: "لأنّ التحقّقَ يستلزم مفتاحَك السرّيّ، ولا ينبغي إدخالُه في أيّ أداةِ ويب مهما كانت." },
    ],
    langs: ["ar", "en"],
    instructionsEn: "Paste the token — it is decoded in your browser and never sent to a server.",
    useStepsEn: [
      "Paste the token, with or without the Bearer prefix.",
      "Read the claims table — the times are converted to dates.",
      "Check the algorithm badge: alg=none means the token carries no signature at all.",
    ],
    howItWorksEn: [
      "This tool decodes but does not verify: verification requires the secret key, and entering your key into a web page is a mistake in itself.",
      "A JWT payload is not encrypted — it is Base64URL that anyone holding the token can read.",
      "The algorithm is shown explicitly, so alg=none is visible at a glance.",
    ],
    load: () => import("@/tools/jwt-decode/tool"),
  }),
  defineTool({
    slug: "cron-explain",
    title: "شارح cron",
    titleEn: "Cron Expression Explainer",
    description: "يترجم تعبيرَ cron إلى جملةٍ عربيّةٍ واضحة، ويعرض المواعيدَ الستّةَ القادمة.",
    descriptionEn: "Turns a cron expression into a plain sentence and lists the next six runs.",
    category: "dev", subcategory: "data", icon: "clock", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["cron", "كرون", "جدولة", "مهامّ", "دوريّ", "توقيت", "خادم", "crontab"],
    keywordsEn: ["cron", "crontab", "schedule", "next run"],
    complexity: "advanced",
    instructions: "اكتب التعبيرَ أو اختر جاهزاً — الشرحُ والمواعيدُ تتحدّث فوراً.",
    howItWorks: [
      "متى قُيّد يومُ الشهر ويومُ الأسبوع معاً جُمع الشرطان بـ«أو» لا بـ«و» — وهذا أشهرُ ما يُخطئ فيه الناس.",
      "المواعيدُ تُحسب بقفز اليوم كلِّه متى لم يطابق، فيبقى الحسابُ فوريّاً مهما ندر الموعد.",
      "التعبيرُ ذو الستّة حقولٍ نمطُ Quartz للثواني، ولا يفهمه cron في يونكس.",
    ],
    faq: [
      { q: "بأيّ توقيتٍ تُحسب المواعيد؟", a: "بتوقيت جهازك. وخادمُك غالباً بتوقيت UTC، فراجع فرقَ المنطقة قبل الاعتماد على الرقم." },
    ],
    useSteps: [
      "اكتب التعبيرَ في الحقل، أو اضغط أحدَ الأزرار الجاهزة.",
      "اقرأ البطاقاتِ الخمسَ فوقه: كلُّ حقلٍ باسمه ومداه المسموح.",
      "راجع الجملةَ العربيّةَ — إن خالفت قصدَك فالتعبيرُ خطأٌ لا الشرح.",
      "تحقّق من المواعيد الستّة القادمة، وانتبه أنّها بتوقيت جهازك لا الخادم.",
    ],
    examples: {
      caption: "مولَّدةٌ من محلّل cron نفسِه، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["التعبير", "بالعربيّة"],
      rows: [
        ["*/15 * * * *", "كلَّ 15 دقيقة، كلَّ يوم."],
        ["0 2 * * *", "الساعة 02:00، كلَّ يوم."],
        ["0 9 * * 1-5", "الساعة 09:00، يومَ الاثنين إلى الجمعة."],
        ["0 0 1 * *", "الساعة 00:00، في اليوم 1 من الشهر."],
        ["15 3 * * 0", "الساعة 03:15، يومَ الأحد."],
      ],
    },
    caveat: "المواعيدُ محسوبةٌ بتوقيت جهازك، وخادمُك غالباً بتوقيت UTC — راجع فرقَ المنطقة قبل الاعتماد على الساعة.",
    demo: { fields: { "cr-in": "0 3 * * 1-5" } },
    langs: ["ar", "en"],
    instructionsEn: "Type an expression or pick a preset — the explanation and the runs update instantly.",
    useStepsEn: [
      "Type the expression, or pick one of the presets.",
      "Read the five field cards above it — each is named with its allowed range.",
      "Check the sentence: if it does not match your intent, the expression is wrong, not the explanation.",
      "Look at the next six runs — they use your device's clock, not the server's.",
    ],
    howItWorksEn: [
      "When day-of-month and day-of-week are both restricted, cron joins them with OR, not AND — the mistake people make most often.",
      "Runs are found by skipping whole non-matching days, so the calculation stays instant however rare the schedule.",
      "A six-field expression is the Quartz seconds form, which Unix cron does not understand.",
    ],
    load: () => import("@/tools/cron-explain/tool"),
  }),
  defineTool({
    slug: "password-gen",
    title: "مولّد كلمات المرور",
    titleEn: "Password Generator",
    description: "كلماتُ مرورٍ من مولّد النظام المعتمَد للتعمية، مع قياسِ العشوائيّة بالبتّات.",
    descriptionEn: "Passwords from the system's cryptographic generator, with strength measured in bits of entropy.",
    category: "dev", subcategory: "security", icon: "shield", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["كلمة مرور", "مولّد", "عشوائيّ", "قويّة", "أمان", "باسوورد", "عشوائيّة"],
    keywordsEn: ["password generator", "random", "entropy", "secure"],
    complexity: "medium",
    capabilities: { share: false },
    instructions: "اضبط الطولَ وما تحويه — تُولَّد خمسٌ لتختار منها.",
    howItWorks: [
      "العشوائيّةُ من crypto.getRandomValues، وهو مولّدُ النظام المعتمَدُ للتعمية لا Math.random.",
      "الاختيارُ يرفض القيمَ الزائدةَ بدل أخذِ باقي القسمة، فلا تميل الكلمةُ إلى أوائل البركة.",
      "العشوائيّةُ بالبتّات = الطول × لوغاريتم حجم البركة — ومنها وحدَها تُقاس القوّة، لا من شكل الكلمة.",
    ],
    faq: [
      { q: "هل تُحفَظ الكلماتُ أو تُرسَل؟", a: "لا شيءَ من ذلك. تُولَّد في متصفّحك وتزول بإغلاق الصفحة، ولا يمرّ منها حرفٌ على أيّ خادم." },
      { q: "أيّهما أهمّ: الطولُ أم الرموز؟", a: "الطول. عشرون حرفاً صغيراً أقوى من ثمانيةٍ بكلّ الرموز، والأهمُّ ألّا تُكرَّر الكلمةُ بين موقعين." },
    ],
    useSteps: [
      "اسحب شريطَ الطول — وهو أهمُّ عاملٍ في القوّة.",
      "أطفئ ما لا يقبله الموقعُ من مجموعات المحارف.",
      "فعّل «بلا محارفَ ملتبسة» إن كنت ستكتبها بيدك أو تمليها على أحد.",
      "انسخ واحدةً من الخمس، أو اضغط «ولّد غيرَها» لخمسٍ جديدة.",
    ],
    examples: {
      caption: "عشوائيّةٌ محسوبةٌ ببركةٍ من ٩٤ محرفاً (صغيرةٌ وكبيرةٌ وأرقامٌ ورموز)، مولَّدةٌ من الأداة نفسِها.",
      columns: ["الطول", "العشوائيّة", "الحكم"],
      rows: [
        ["8 محارف", "52 بتّاً", "مقبولةٌ لحسابٍ غير مهمّ"],
        ["12 محرفاً", "79 بتّاً", "جيّدة"],
        ["16 محرفاً", "105 بتّاً", "قويّةٌ جدّاً"],
        ["20 محرفاً", "131 بتّاً", "قويّةٌ جدّاً"],
        ["24 محرفاً", "157 بتّاً", "قويّةٌ جدّاً"],
      ],
    },
    deepDive: [
      {
        heading: "لماذا يُقاس بالبتّات لا بعدّاد «ضعيف/قويّ» الملوّن",
        body: "العدّاداتُ الملوّنةُ في نماذج التسجيل تقيس الشكلَ لا القوّة: تعطي Passw0rd! درجةً عالية لأنّ فيها حرفاً كبيراً ورقماً ورمزاً، وهي في قوائم الكسر الأولى. أمّا العشوائيّةُ بالبتّات فتقيس عددَ الاحتمالات التي على المهاجم أن يجرّبها: كلُّ بتٍّ يضاعف العمل. ولذلك كلمةٌ من ١٦ محرفاً عشوائيّاً (١٠٥ بتّات) خارجَ متناول أيّ حاسوبٍ قائمٍ اليوم، مهما بدت «غيرَ منظّمة».",
      },
      {
        heading: "الطولُ يغلب التعقيد",
        body: "زيادةُ محرفٍ واحدٍ إلى الطول تضرب عددَ الاحتمالات في حجم البركة كلِّها، بينما إضافةُ مجموعةِ رموزٍ تكبّر البركةَ مرّةً واحدة. عشرون حرفاً صغيراً فقط تعطي ٩٤ بتّاً، وثمانيةٌ بكلّ الرموز تعطي ٥٢. فإن خيّرك موقعٌ بين الطول والتعقيد فخذ الطول. وأهمُّ من هذا كلِّه ألّا تُكرَّر الكلمةُ بين موقعين، فتسريبُ موقعٍ واحدٍ يفتح الباقي كلَّه.",
      },
    ],
    langs: ["ar", "en"],
    instructionsEn: "Set the length and what it may contain — five passwords are generated for you to pick from.",
    useStepsEn: [
      "Drag the length slider — length is the single biggest factor in strength.",
      "Turn off any character set the site will not accept.",
      "Enable \"no look-alike characters\" if you will type or dictate the password.",
      "Copy one of the five, or generate a fresh set.",
    ],
    howItWorksEn: [
      "Randomness comes from crypto.getRandomValues — the system's cryptographic generator, not Math.random.",
      "Values above the fold are rejected rather than reduced modulo, so the password never leans toward the start of the pool.",
      "Entropy in bits = length × log2(pool size) — strength is measured from that alone, never from how the password looks.",
    ],
    load: () => import("@/tools/password-gen/tool"),
  }),
  defineTool({
    slug: "hash",
    title: "بصمة نصٍّ أو ملفّ",
    titleEn: "Hash Generator (SHA)",
    description: "بصماتُ SHA لنصٍّ أو ملفٍّ في متصفّحك، مع مقارنةٍ ببصمةٍ منشورة.",
    descriptionEn: "SHA digests for text or a file in your browser, with a comparison against a published digest.",
    category: "dev", subcategory: "security", icon: "fingerprint", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["بصمة", "hash", "sha256", "sha512", "تحقّق", "سلامة", "checksum", "ملفّ"],
    keywordsEn: ["hash", "sha256", "checksum", "file integrity"],
    complexity: "medium",
    instructions: "اختر المصدرَ والخوارزميّة — الملفُّ يُقرأ في متصفّحك ولا يُرفَع.",
    howItWorks: [
      "الحسابُ عبر crypto.subtle في المتصفّح، فلا يغادر الملفُّ جهازَك مهما كبر.",
      "‏MD5 غيرُ متاحٍ لأنّ المتصفّحَ لا يوفّره — وهو مكسورٌ أصلاً.",
      "البصمةُ ليست حمايةَ كلماتِ مرور: تلك تحتاج argon2 أو bcrypt بملحٍ وبطءٍ مقصود.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Choose the source and the algorithm — the file is read in your browser and never uploaded.",
    useStepsEn: [
      "Choose text or a file.",
      "Pick the algorithm — SHA-256 unless you have a reason.",
      "Paste the published digest below to confirm the file arrived intact.",
    ],
    howItWorksEn: [
      "Computed with crypto.subtle in the browser, so the file never leaves your machine however large it is.",
      "MD5 is unavailable because the browser does not provide it — and it is broken anyway.",
      "A hash is not password protection: passwords need argon2 or bcrypt, with a salt and deliberate slowness.",
    ],
    load: () => import("@/tools/hash/tool"),
  }),
  defineTool({
    slug: "uuid",
    title: "مولّد UUID",
    titleEn: "UUID Generator",
    description: "توليدُ v4 العشوائيّ وv7 الزمنيّ، وفحصُ أيِّ معرّفٍ لمعرفة إصداره وزمنه.",
    descriptionEn: "Generate random v4 and time-ordered v7, and inspect any identifier for its version and timestamp.",
    category: "dev", subcategory: "data", icon: "idcard", version: "1.1.0", publishedAt: "2026-08-30",
    keywords: ["uuid", "معرّف", "guid", "عشوائيّ", "مفتاح", "قاعدة بيانات", "v4", "v7"],
    keywordsEn: ["uuid generator", "guid", "uuid v4", "uuid v7"],
    complexity: "medium",
    capabilities: { share: false },
    instructions: "اختر الإصدارَ والعدد — أو ألصق معرّفاً في خانة الفحص.",
    howItWorks: [
      "‏v4 عشوائيٌّ بالكامل (١٢٢ بتّاً) وهو الأشيع، لكنّه مفتاحاً أساسيّاً يبعثر فهرسَ القاعدة.",
      "‏v7 يبدأ بزمن يونكس بالمللي، فيُلحِق الجديدَ بآخر الفهرس كالرقم المتسلسل مع بقائه غيرَ قابلٍ للتخمين.",
      "الطابعُ الزمنيُّ وحدَه لا يرتّب: عشراتُ المعرّفات تُولَّد في المللي الواحدة فتتساوى طوابعُها. لذلك يحمل v7 هنا عدّاداً يتزايد داخل المللي — الطريقةَ الأولى في RFC 9562.",
      "الفحصُ يقرأ الإصدارَ والنمطَ من موضعهما المحدَّد في المعرّف، ويستخرج زمنَ v7.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Pick the version and how many — or paste an identifier into the inspect field.",
    useStepsEn: [
      "Choose v4, v7, or the nil identifier.",
      "Pick how many to generate.",
      "Copy one, or all of them.",
      "Paste any UUID into the inspect field to see its version and, for v7, its timestamp.",
    ],
    howItWorksEn: [
      "v4 is fully random (122 bits) and the most common, but as a primary key it scatters the database index.",
      "v7 begins with Unix time in milliseconds, so it appends to the end of the index like an auto-increment while staying unguessable.",
      "The timestamp alone does not order them: dozens are generated within the same millisecond, so v7 here carries a counter that increments within the millisecond (RFC 9562 method 1).",
      "The inspector reads the version and variant from their fixed positions in the identifier.",
    ],
    load: () => import("@/tools/uuid/tool"),
  }),

  /* ————— تصميم ————— */
  defineTool({
    slug: "color-convert",
    title: "محوّل الألوان",
    titleEn: "Color Converter",
    description: "‏HEX وRGB وHSL وOKLCH لأيّ لون، مع إضاءته الإدراكيّة وإضاءة WCAG.",
    descriptionEn: "HEX, RGB, HSL and OKLCH for any colour, with its perceptual lightness and its WCAG luminance.",
    category: "design", subcategory: "color", icon: "droplet", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["لون", "hex", "rgb", "hsl", "oklch", "تحويل ألوان", "كود لون"],
    keywordsEn: ["color converter", "hex to rgb", "oklch", "hsl"],
    complexity: "medium",
    instructions: "اكتب اللونَ بأيّ صيغةٍ أو استعمل المنتقي — تُعرض الصيغُ كلُّها معاً.",
    howItWorks: [
      "يقبل hex بثلاث خاناتٍ وأربعٍ وستٍّ وثمانٍ، وrgb() وhsl() بصيغتَيهما القديمة والحديثة، وأسماءَ ألوانٍ عربيّةً وإنكليزيّة.",
      "إضاءةُ OKLCH إدراكيّة: لونان بها متساويان يبدوان متساويَي السطوع للعين — بخلاف إضاءة HSL الحسابيّة.",
      "إضاءةُ WCAG رقمٌ فيزيائيٌّ لا يُستعمل إلّا في حساب التباين.",
    ],
    useSteps: [
      "اكتب اللونَ بأيّ صيغةٍ تعرفها، أو اضغط المربّعَ الملوّنَ لتنتقيه بصريّاً.",
      "اقرأ الصيغَ الأربعَ معاً وانسخ ما يلزم مشروعَك.",
      "راجع البلاطاتِ أسفلَه لتعرف إضاءةَ اللون وتشبّعَه وصبغتَه.",
    ],
    examples: {
      caption: "مولَّدةٌ من مكتبة الألوان نفسِها، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["HEX", "RGB", "HSL", "OKLCH"],
      rows: [
        ["#3366cc", "rgb(51 102 204)", "hsl(220 60% 50%)", "oklch(53.2% 0.168 262.3)"],
        ["#ff8800", "rgb(255 136 0)", "hsl(32 100% 50%)", "oklch(74.4% 0.181 56.5)"],
        ["#12b886", "rgb(18 184 134)", "hsl(162 82% 40%)", "oklch(69.5% 0.143 164.9)"],
      ],
    },
    nextSteps: [
      { slug: "contrast", label: "افحص تباينَ هذا اللون", labelEn: "Check this colour's contrast" },
      { slug: "palette", label: "ولّد لوحةً منه", labelEn: "Generate a palette from it" },
    ],
    demo: { fields: { "cc-in": "#3366cc" } },
    langs: ["ar", "en"],
    instructionsEn: "Type a colour in any notation, or use the picker — every notation is shown together.",
    useStepsEn: [
      "Type the colour in whatever notation you know, or click the swatch to pick it visually.",
      "Copy whichever of the four notations your project needs.",
      "Read the tiles below for the colour's lightness, chroma and hue.",
    ],
    howItWorksEn: [
      "It accepts 3-, 4-, 6- and 8-digit hex, rgb() and hsl() in both the legacy and modern syntax, and colour names.",
      "OKLCH lightness is perceptual: two colours at the same value look equally bright — unlike HSL lightness, which is arithmetic.",
      "WCAG luminance is a physical number used only in contrast calculations.",
    ],
    load: () => import("@/tools/color-convert/tool"),
  }),
  defineTool({
    slug: "contrast",
    title: "فاحص التباين",
    titleEn: "Contrast Checker (WCAG)",
    description: "نسبةُ التباين وحكمُ AA وAAA، مع أقربِ لونٍ يمرّ بالصبغة نفسِها.",
    descriptionEn: "Contrast ratio and the AA/AAA verdict, plus the nearest passing colour in the same hue.",
    category: "design", subcategory: "color", icon: "contrast", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تباين", "إتاحة", "wcag", "قابلية القراءة", "aa", "aaa", "عمى ألوان", "وضوح"],
    keywordsEn: ["contrast checker", "wcag", "accessibility", "a11y"],
    complexity: "medium",
    relatedToolIds: ["color-convert", "palette"],
    instructions: "اختر لونَ النصّ والخلفيّة — الحكمُ والمعاينةُ فوريّان.",
    howItWorks: [
      "النسبةُ محسوبةٌ بمعادلة WCAG 2.1: إضاءتان نسبيّتان مضافٌ إليهما ٠٫٠٥ ثمّ قسمة.",
      "«نصٌّ كبير» يعني ١٨pt فأكبر أو ١٤pt عريضاً — والخطُّ العربيُّ يحتاج غالباً حجماً أكبرَ من نظيره اللاتينيّ.",
      "الاقتراحُ يزحزح إضاءةَ OKLCH وحدَها، فتبقى صبغةُ علامتك التجاريّة وتشبّعُها.",
    ],
    faq: [
      { q: "هل يكفي أن يمرّ AA؟", a: "‏AA هو الحدُّ القانونيُّ في أكثر التشريعات، وAAA هدفٌ للمتن الطويل. وما دون 3:1 لا يصلح حتّى لحدود الحقول والأيقونات." },
    ],
    useSteps: [
      "ضع لونَ النصّ ولونَ الخلفيّة — أو اضغط ⇄ لتجرّبهما معكوسين.",
      "اقرأ النسبةَ وقائمةَ العتبات: كلُّ سطرٍ يقول ما الذي مرَّ وما الذي سقط.",
      "إن سقط النصُّ العاديّ، انسخ اللونَ المقترحَ — صبغتُه صبغةُ لونك، والإضاءةُ وحدَها تغيّرت.",
    ],
    examples: {
      caption: "أحكامٌ محسوبةٌ بالأداة نفسِها، ويتحقّق منها اختبارٌ آليّ.",
      columns: ["النصّ على الخلفيّة", "النسبة", "الحكم"],
      rows: [
        ["أسود على أبيض", "21.00:1", "يمرّ AAA"],
        ["أبيض على #1a1a1a", "17.40:1", "يمرّ AAA"],
        ["#3366cc على أبيض", "5.37:1", "يمرّ AA"],
        ["#767676 على أبيض", "4.54:1", "يمرّ AA بالكاد"],
        ["#ffb020 على أبيض", "1.83:1", "لا يكفي لشيء"],
      ],
    },
    deepDive: [
      {
        heading: "الأصفرُ والبرتقاليُّ فخُّ العلامات التجاريّة",
        body: "الكهرمانُ والأصفرُ يبدوان واضحين للعين على الأبيض لأنّهما ساطعان، لكنّ سطوعَهما هو المشكلة: التباينُ فرقُ إضاءةٍ لا فرقُ صبغة، ولونٌ ساطعٌ على خلفيّةٍ ساطعةٍ تباينُه منخفض. ولهذا يسقط #ffb020 على الأبيض عند 1.83:1 — أي أنّه لا يصلح نصّاً ولا حدَّ حقلٍ ولا أيقونة. والحلُّ ليس ترك اللون بل استعمالُه خلفيّةً بنصٍّ داكنٍ فوقه.",
      },
      {
        heading: "لماذا يزحزح الاقتراحُ الإضاءةَ وحدَها",
        body: "لو بحثنا عن «أقرب لونٍ يمرّ» في فضاء RGB لخرجنا بلونٍ آخرَ بالكلّيّة — أخضرَ بدل الأزرق مثلاً. أمّا الزحزحةُ في OKLCH فتغيّر الإضاءةَ وتبقي الصبغةَ والتشبّع، فيظل اللونُ الناتجُ من عائلة علامتك التجاريّة. وهذا هو الفرقُ بين أداةٍ تقول «استعمل لوناً آخر» وأداةٍ تقول «استعمل لونَك أغمقَ بهذا القدر».",
      },
    ],
    demo: { fields: { "ct-fg": "#ffb020", "ct-bg": "#ffffff" } },
    langs: ["ar", "en"],
    instructionsEn: "Set the text and background colours — the ratio and the WCAG verdict update instantly.",
    useStepsEn: [
      "Set the text colour and the background — or press ⇄ to try them the other way round.",
      "Read the ratio and the threshold list: each line says what passes and what fails.",
      "If body text fails, copy the suggested colour — its hue is yours, only the lightness moved.",
    ],
    howItWorksEn: [
      "The ratio uses the WCAG 2.1 formula: two relative luminances, each plus 0.05, divided.",
      "\"Large text\" means 18pt (≈24px) or larger, or 14pt (≈18.7px) bold.",
      "The suggestion shifts OKLCH lightness only, so your brand hue and chroma survive.",
    ],
    load: () => import("@/tools/contrast/tool"),
  }),
  defineTool({
    slug: "palette",
    title: "مولّد لوحة الألوان",
    titleEn: "Color Palette Generator",
    description: "تناسقاتٌ من لونٍ واحد وسُلَّمٌ من ٥٠ إلى ٩٥٠ — بخطواتٍ متساويةٍ في العين.",
    descriptionEn: "Harmonies from one colour and a 50–950 scale — with perceptually even steps.",
    category: "design", subcategory: "color", icon: "swatches", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["لوحة ألوان", "تناسق", "متتام", "سلم ألوان", "نظام تصميم", "متغيرات css", "هوية"],
    keywordsEn: ["color palette", "harmony", "color scale", "design tokens"],
    complexity: "advanced",
    relatedToolIds: ["color-convert", "contrast"],
    instructions: "اختر لوناً أساساً ونوعَ التناسق — والسُّلَّمُ جاهزٌ للّصق متغيّراتِ CSS.",
    howItWorks: [
      "الدورانُ والتدرّجُ يجريان في OKLCH لا HSL، فخطواتُ السُّلَّم متساويةٌ إدراكيّاً ولا تجد قفزةً هنا وسكوناً هناك.",
      "ما خرج من الألوان عن مدى الشاشة يُردّ إليه بخفض التشبّع لا بقصّ القنوات — فتبقى الصبغةُ صحيحةً ويبقى المتتامُّ متتامّاً.",
      "التشبّعُ يخفّ عند طرفَي السُّلَّم كما في سلالم أنظمة التصميم الحقيقيّة، فلا تصير الدرجاتُ الفاتحةُ فاقعة.",
    ],
    nextSteps: [
      { slug: "contrast", label: "افحص تباينَ هذه الألوان", labelEn: "Check the contrast of these colours" },
      { slug: "gradient", label: "ابنِ تدرّجاً منها", labelEn: "Build a gradient from them" },
    ],
    demo: { fields: { "pl-in": "#12b886" } },
    langs: ["ar", "en"],
    instructionsEn: "Pick a base colour and a harmony — the scale below is ready to paste as CSS variables.",
    useStepsEn: [
      "Pick the base colour, or use the picker.",
      "Choose a harmony — each one is a different relationship on the colour wheel.",
      "Click any swatch to copy it, or copy the whole set of CSS variables.",
    ],
    howItWorksEn: [
      "Rotation and ramping happen in OKLCH, not HSL, so the scale steps are perceptually even.",
      "Colours outside the screen gamut are brought back by reducing chroma, never by clipping channels — so the hue stays correct.",
      "Chroma eases off at both ends of the ramp, the way real design-system scales do.",
    ],
    load: () => import("@/tools/palette/tool"),
  }),
  defineTool({
    slug: "gradient",
    title: "مولّد التدرّجات",
    titleEn: "CSS Gradient Generator",
    description: "تدرّجٌ خطّيٌّ أو شعاعيٌّ بمزجٍ في OKLab — بلا المنطقة الموحلة التي يقع فيها sRGB.",
    descriptionEn: "A linear or radial gradient mixed in OKLab — without the muddy middle sRGB produces.",
    category: "design", subcategory: "color", icon: "gradient", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تدرج", "gradient", "css", "خلفية", "مزج ألوان", "لينير"],
    keywordsEn: ["css gradient", "linear gradient", "oklab", "color mixing"],
    complexity: "medium",
    relatedToolIds: ["palette", "color-convert"],
    instructions: "اختر اللونين والزاوية — وانسخ سطرَ CSS مع بديلٍ متوافقٍ مع المتصفّحات القديمة.",
    howItWorks: [
      "المزجُ في sRGB يجمع الأرقامَ لا الألوان، فيهبط التشبّعُ في المنتصف بين صبغتين متقابلتين ويظهر رماديٌّ موحل.",
      "المزجُ في OKLab يمرّ بالصبغات الوسيطة كما تتوقّعها العين — جرّب أزرقَ وأصفرَ لترى الفرق.",
      "المعاينةُ محسوبةٌ بعيّناتٍ في OKLab، فتُري النتيجةَ الصحيحةَ حتّى في متصفّحٍ لا يدعم `in oklab`.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Pick two colours and an angle — copy the CSS line, with a fallback for older browsers.",
    useStepsEn: [
      "Set the two colours.",
      "Choose linear or radial, and the angle.",
      "Copy the CSS — and the fallback line if you support older browsers.",
    ],
    howItWorksEn: [
      "Mixing in sRGB adds numbers rather than colours, so chroma collapses between two opposing hues and grey appears in the middle.",
      "Mixing in OKLab passes through the intermediate hues the eye expects — try blue to yellow to see it.",
      "The preview is computed from OKLab samples, so it shows the true result even in a browser without `in oklab`.",
    ],
    load: () => import("@/tools/gradient/tool"),
  }),
  defineTool({
    slug: "image-resize",
    title: "تصغير الصور وتحويلها",
    titleEn: "Image Resizer & Converter",
    description: "تصغيرٌ وتحويلٌ إلى WebP أو JPEG أو PNG في متصفّحك — بلا رفعٍ إلى أيّ خادم.",
    descriptionEn: "Resize and convert to WebP, JPEG or PNG in your browser — nothing is uploaded.",
    category: "design", subcategory: "images", icon: "resize", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["تصغير صورة", "ضغط صورة", "webp", "تحويل صيغة", "حجم الصورة", "أبعاد", "jpeg"],
    keywordsEn: ["resize image", "compress image", "webp converter", "image size"],
    complexity: "medium",
    capabilities: { share: false },
    instructions: "اختر صورةً من جهازك، ثمّ العرضَ والصيغة — والتنزيلُ من متصفّحك مباشرةً.",
    howItWorks: [
      "الرسمُ والتحويلُ يجريان على canvas في متصفّحك، فلا تُرفَع صورتُك إلى أيّ خادم.",
      "‏WebP أصغرُ من JPEG بجودةٍ مماثلة، و٧٥–٨٥٪ هو موضعُ التوازن عادةً — وما فوق ٩٠ يكبّر الملفَّ بلا فرقٍ مرئيّ.",
      "الرسمُ على canvas يمحو بيانات EXIF — موقعَ التصوير وطرازَ الجهاز، وهذه ميزةٌ لا نقص.",
      "لا تكبيرَ فوق الأصل إلّا بطلبٍ صريح، فالتكبيرُ لا يخلق تفصيلاً غيرَ موجود.",
    ],
    faq: [
      { q: "هل تُرفَع صورتي؟", a: "لا. كلُّ العمل على canvas في متصفّحك، والملفُّ الناتج يُبنى محلّيّاً وينزل من الجهاز نفسِه." },
      { q: "لماذا صار الناتجُ أكبرَ من الأصل أحياناً؟", a: "لأنّ الأصلَ مضغوطٌ جيّداً أصلاً وأنت تعيد ترميزَه. متى ظهر ذلك فأبقِ الأصل." },
    ],
    nextSteps: [
      { slug: "favicon", label: "اصنع منها أيقونةَ موقع", labelEn: "Turn it into a site icon" },
      { slug: "image-colors", label: "استخرج ألوانَها", labelEn: "Extract its colours" },
    ],
    langs: ["ar", "en"],
    instructionsEn: "Choose an image from your device, then a width and a format — the download comes straight from your browser.",
    useStepsEn: [
      "Pick an image from your device.",
      "Choose the output width and format.",
      "Adjust quality for the lossy formats.",
      "Download the result — it is built locally and never leaves the machine.",
    ],
    howItWorksEn: [
      "Drawing and conversion happen on a canvas in your browser, so your image is never uploaded.",
      "WebP is smaller than JPEG at comparable quality; 75–85% is usually the balance point.",
      "Drawing on a canvas strips EXIF — location, device and date — which is a privacy feature, not a loss.",
      "Upscaling beyond the original is off unless you ask: enlarging cannot create detail that is not there.",
    ],
    load: () => import("@/tools/image-resize/tool"),
  }),
  defineTool({
    slug: "image-colors",
    title: "ألوانٌ من صورة",
    titleEn: "Extract Colors from Image",
    description: "اللوحةُ السائدةُ في صورةٍ مع نصيبِ كلِّ لون — تُستخرج في متصفّحك.",
    descriptionEn: "The dominant palette of an image with each colour's share — extracted in your browser.",
    category: "design", subcategory: "images", icon: "eyedropper", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["ألوان من صورة", "لوحة", "استخراج لون", "هوية", "شعار", "قطارة"],
    keywordsEn: ["extract colors", "image palette", "dominant colors"],
    complexity: "medium",
    capabilities: { share: false },
    relatedToolIds: ["palette", "color-convert"],
    instructions: "اختر صورةً وعددَ الألوان — انقر أيَّ رقعةٍ لنسخ قيمتها.",
    howItWorks: [
      "تُصغَّر الصورةُ إلى ١٦٠ بكسلاً للعيّنة، فتبقى النتيجةُ فوريّةً مهما كبر الأصل.",
      "الألوانُ تُجمَع في مكعّباتٍ من ٣٢ درجةً ثمّ تُرتَّب بالتكرار — طريقةٌ حتميّة: الصورةُ نفسُها تعطي اللوحةَ نفسَها دائماً.",
      "البكسلاتُ الشفّافةُ تُتجاهَل، فلا يلوّث الشعارُ ذو الخلفيّة الشفّافة لوحتَه بلونٍ وهميّ.",
    ],
    nextSteps: [
      { slug: "palette", label: "ابنِ سُلَّماً كاملاً من أحد هذه الألوان", labelEn: "Build a full scale from one of these" },
      { slug: "contrast", label: "افحص تباينَها مع الأبيض", labelEn: "Check their contrast against white" },
    ],
    langs: ["ar", "en"],
    instructionsEn: "Pick an image and how many colours you want — click any swatch to copy it.",
    useStepsEn: [
      "Pick an image from your device.",
      "Choose how many colours to extract.",
      "Click a swatch to copy its hex, or copy the whole set of CSS variables.",
    ],
    howItWorksEn: [
      "The image is sampled down to 160px, so the result is instant no matter how large the original.",
      "Colours are bucketed into 32-step cubes and ranked by frequency — a deterministic method, so the same image always gives the same palette.",
      "Transparent pixels are ignored, so a logo on a transparent background does not pick up a phantom colour.",
    ],
    load: () => import("@/tools/image-colors/tool"),
  }),
  defineTool({
    slug: "favicon",
    title: "مولّد أيقونة الموقع",
    titleEn: "Favicon Generator",
    description: "كلُّ المقاسات من شعارٍ أو حرف، مع وسوم <head> وملفِّ البيان جاهزين.",
    descriptionEn: "Every size from a logo or a letter, with the <head> tags and the manifest ready to paste.",
    category: "design", subcategory: "images", icon: "appicon", version: "1.0.0", publishedAt: "2026-08-30",
    keywords: ["أيقونة موقع", "favicon", "شعار", "لسان المتصفح", "apple touch icon", "manifest", "pwa"],
    keywordsEn: ["favicon generator", "apple touch icon", "web manifest", "app icon"],
    complexity: "medium",
    capabilities: { share: false },
    relatedToolIds: ["image-resize", "color-convert"],
    instructions: "اختر حرفاً أو شعاراً واضبط اللونَ والاستدارة — ثمّ نزّل المقاسات.",
    howItWorks: [
      "كلُّ مقاسٍ يُرسَم على canvas على حدة، فالحرفُ يبقى حادّاً في ١٦ بكسلاً بدل أن يُصغَّر عن ٥١٢ فيهترئ.",
      "لا تُولَّد صيغةُ ICO: المتصفّحاتُ الحديثة تقبل PNG مباشرةً، ولم تعد ICO لازمةً إلّا لمتصفّحاتٍ قديمةٍ جدّاً.",
      "أيقونةُ ٥١٢ يبني منها الهاتفُ شاشةَ الإقلاع حين يُضاف الموقعُ إلى الشاشة الرئيسة.",
    ],
    langs: ["ar", "en"],
    instructionsEn: "Choose a letter or a logo, set the colour and the corner radius, then download the sizes.",
    useStepsEn: [
      "Choose a letter or upload a logo.",
      "Set the background colour, the corner radius and the padding.",
      "Download each size, or all of them at once.",
      "Paste the <head> tags and the manifest into your site.",
    ],
    howItWorksEn: [
      "Each size is drawn on its own canvas, so a letter stays sharp at 16px instead of being shrunk from 512 and going ragged.",
      "No ICO is produced: modern browsers accept PNG directly, and ICO is only needed by very old ones.",
      "The 512 icon is what a phone uses to build the splash screen when your site is added to the home screen.",
    ],
    load: () => import("@/tools/favicon/tool"),
  }),
];

export const registryErrorsAtBoot = TOOLS.length === 0 ? ["السجلّ فارغ"] : [];
